In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''

In [2]:
df = pd.read_csv(base_path + 'df21011_2.csv')
df

             GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
0              0000  2021-09-11         1    1800.0      1800
1              0000  2021-09-28         3    1800.0      5400
2              0000  2021-12-05         1    1800.0      1800
3              0000  2021-12-13         1    1800.0      1800
4              0000  2022-01-07         1    1800.0      1800
...             ...         ...       ...       ...       ...
1776826    히츨러수수깡캔디  2021-10-08         1    3500.0      3500
1776827    히츨러수수깡캔디  2021-10-14         1    3500.0      3500
1776828    히츨러수수깡캔디  2021-12-03         2    3500.0      7000
1776829    히츨러수수깡캔디  2021-12-04         2    3500.0      7000
1776830  히포LED파인등기구  2022-03-03         1   11500.0     11500

[1776831 rows x 5 columns]

In [3]:
df.sort_values('SALE_QTY', ascending=True).head(50)

                   GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1100633        오뚜기컵밥춘천닭갈비  2022-08-05         0    3350.0         0
1103035        오뚜기콩국수라면멀티  2021-12-06         0    5780.0         0
1472427               콩기름  2022-05-17         0   20600.0         0
1773631        흑마늘힐링덕훈제오리  2022-08-21         0    9900.0         0
1773571        흑마늘힐링덕훈제오리  2022-05-24         0    7900.0         0
1248671             제주용암수  2021-09-05         0    8000.0         0
1146977           오리온오징어톡  2021-10-26         0    2100.0         0
1636164         피지파워젤오리지널  2022-04-04         0   13200.0         0
1707727           해태에이스샌드  2022-01-18         0    1200.0         0
247959           농심수미칩어니언  2022-07-02         0    1980.0         0
1773314  흑대추방울토마토500g1팩행사  2022-02-08         0    4980.0         0
1335915        청정원가쓰오우동2인  2022-04-24         0    6200.0         0
82525        CJ햄스빌두툼한굿베이컨  2022-03-21         0    7000.0         0
82526        CJ햄스빌두툼한굿베이컨  2022-03-27         0    7000.0         0
1257568       존쿡델리미트스모크브랏  2022-05-31         0   14800.0         0
1018399          오뚜기감자떡만두  2021-11-15         0   19200.0         0
1717915              해태포키  2022-04-13         0    6520.0         0
608271          면사랑냉동함흥냉면  2021-12-22         0    9700.0         0
329702           대한또띠아8인치  2022-01-30         0    5500.0         0
329703           대한또띠아8인치  2022-02-03         0   11000.0         0
142756           고메토마토미트볼  2021-11-20         0    3150.0         0
86750       CJ햇반컵반고추장제육덮밥  2022-02-17         0    6200.0         0
1249186        제주향당근1봉국내산  2022-04-13         0    2980.0         0
106705          LG퐁퐁베이킹소다  2022-01-30         0    4960.0         0
320310          대림한입쌀조랭이떡  2022-01-14         0    2200.0         0
320311          대림한입쌀조랭이떡  2022-01-20         0    2200.0         0
1140714         오리온쌀쿠키단호박  2022-01-21         0    3960.0         0
1140730          오리온쌀쿠키우유  2022-01-18         0    1980.0         0
1546067            티룸진저레몬  2022-01-18         0    1350.0         0
1166666         오양수제모둠소세지  2022-09-01         0    5980.0         0
531240       롯데칸타타카라멜마키아또  2021-10-27         0    1700.0         0
558287             리빙키친타올  2021-10-11         0   10800.0         0
1749518         호밍스소고기볶음밥  2022-08-03         0    5680.0         0
817750              샘표맛간장  2022-03-23         0   11800.0         0
1009104             오딸기송이  2022-04-12         0    4200.0         0
1494604       크라운콘초헤이즐넛초코  2021-10-14         0    2100.0         0
313835           대림알뜰어묵사각  2021-12-19         0    7200.0         0
1757445      홍감자10kg1박스행사  2022-08-07         0   19600.0         0
608481           면사랑사누끼우동  2022-05-02         0    7400.0         0
1670996             한성크래미  2021-09-30         0    3250.0         0
1670997             한성크래미  2021-10-04         0    1300.0         0
901225             스리라차소스  2022-02-24         0   11700.0         0
1103156            오뚜기콩기름  2022-05-20         0   12760.0         0
1074923       오뚜기오쉐프찹쌀탕수육  2022-04-04         0    9900.0         0
621497           몬라이스누들3m  2022-06-10         0    4560.0         0
1147225          오리온와우쿨소다  2022-03-15         0     400.0         0
778252         사조로하이팝콘카라멜  2022-02-19         0    1150.0         0
1147224          오리온와우쿨소다  2022-01-27         0     800.0         0
457353          롯데꼬깔새우마요맛  2022-07-04         0    1100.0         0
1487946        크라운새콤달콤포켓몬  2022-02-08         0    3600.0         0

In [4]:
df

             GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
0              0000  2021-09-11         1    1800.0      1800
1              0000  2021-09-28         3    1800.0      5400
2              0000  2021-12-05         1    1800.0      1800
3              0000  2021-12-13         1    1800.0      1800
4              0000  2022-01-07         1    1800.0      1800
...             ...         ...       ...       ...       ...
1776826    히츨러수수깡캔디  2021-10-08         1    3500.0      3500
1776827    히츨러수수깡캔디  2021-10-14         1    3500.0      3500
1776828    히츨러수수깡캔디  2021-12-03         2    3500.0      7000
1776829    히츨러수수깡캔디  2021-12-04         2    3500.0      7000
1776830  히포LED파인등기구  2022-03-03         1   11500.0     11500

[1776831 rows x 5 columns]

In [5]:
df = df[df.SALE_QTY > 1]

In [6]:
df

                GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1                 0000  2021-09-28         3    1800.0      5400
15                0000  2022-05-26         2    3600.0      3600
19                0000  2022-07-28         2    1800.0      3600
21                0000  2022-08-14         2    1800.0      3600
23       0241405572666  2022-06-22         2     900.0      1800
...                ...         ...       ...       ...       ...
1776816       히츨러수수깡캔디  2021-09-01         2    7000.0      7000
1776817       히츨러수수깡캔디  2021-09-06         2    7000.0      7000
1776825       히츨러수수깡캔디  2021-09-26         2    7000.0      7000
1776828       히츨러수수깡캔디  2021-12-03         2    3500.0      7000
1776829       히츨러수수깡캔디  2021-12-04         2    3500.0      7000

[943752 rows x 5 columns]

In [7]:
df.sort_values('SALE_QTY', ascending=True).head(50)

               GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1776829      히츨러수수깡캔디  2021-12-04         2    3500.0      7000
1151331      오리온촉촉초코칩  2021-11-15         2    5960.0      5960
1151332      오리온촉촉초코칩  2021-11-16         2    5960.0      5960
1151341      오리온촉촉초코칩  2021-12-12         2    5960.0      5960
482336    롯데빼빼로3번들꼬아크  2022-04-05         2    5960.0      5960
1151347      오리온촉촉초코칩  2021-12-19         2    5960.0      5960
482331    롯데빼빼로3번들꼬아크  2022-03-31         2    5960.0      5960
1151349      오리온촉촉초코칩  2021-12-22         2    5960.0      5960
1151355      오리온촉촉초코칩  2021-12-30         2    5960.0      5960
1151330      오리온촉촉초코칩  2021-11-14         2    5960.0      5960
1151360      오리온촉촉초코칩  2022-01-04         2    5960.0      5960
1151363      오리온촉촉초코칩  2022-01-07         2    5960.0      5960
482317    롯데빼빼로3번들꼬아크  2022-03-16         2    5960.0      5960
482314    롯데빼빼로3번들꼬아크  2022-03-13         2    5960.0      5960
1151369      오리온촉촉초코칩  2022-01-13         2    5960.0      5960
1151372      오리온촉촉초코칩  2022-01-16         2    5960.0      5960
482310    롯데빼빼로3번들꼬아크  2022-03-09         2    5960.0      5960
482309    롯데빼빼로3번들꼬아크  2022-03-08         2    5960.0      5960
482308    롯데빼빼로3번들꼬아크  2022-03-07         2    5960.0      5960
482320    롯데빼빼로3번들꼬아크  2022-03-19         2    5960.0      5960
482343    롯데빼빼로3번들꼬아크  2022-04-13         2    5960.0      5960
1151322      오리온촉촉초코칩  2021-10-09         2    5960.0      5960
1151321      오리온촉촉초코칩  2021-10-08         2    5960.0      5960
482399        롯데빼빼로기획  2021-09-08         2    5960.0      5960
1151218   오리온초코파이민트초코  2021-09-09         2    5960.0      5960
482387    롯데빼빼로3번들꼬아크  2022-06-26         2    5960.0      5960
482386    롯데빼빼로3번들꼬아크  2022-06-25         2    5960.0      5960
482385    롯데빼빼로3번들꼬아크  2022-06-24         2    5960.0      5960
482376    롯데빼빼로3번들꼬아크  2022-05-29         2    5960.0      5960
1151225  오리온초코파이베리쇼콜라  2022-01-23         2   10300.0     10300
482368    롯데빼빼로3번들꼬아크  2022-05-15         2    5960.0      5960
1151233  오리온초코파이베리쇼콜라  2022-02-04         2   10300.0     10300
1151242  오리온초코파이베리쇼콜라  2022-02-24         2   10300.0     10300
1151253     오리온초코파이수박  2022-07-21         2    8560.0      8560
1151264    오리온초코파이콘그림  2021-12-22         2    9600.0      9600
1151268    오리온초코파이콘그림  2022-01-21         2    9600.0      9600
1151272    오리온초코파이콘그림  2022-03-04         2    4800.0      9600
1151297      오리온촉촉초코칩  2021-09-04         2    5960.0      5960
1151298      오리온촉촉초코칩  2021-09-05         2    5960.0      5960
1151302      오리온촉촉초코칩  2021-09-10         2    5960.0      5960
482349    롯데빼빼로3번들꼬아크  2022-04-21         2    5960.0      5960
482348    롯데빼빼로3번들꼬아크  2022-04-18         2    5960.0      5960
1151378      오리온촉촉초코칩  2022-01-23         2    5960.0      5960
1151379      오리온촉촉초코칩  2022-01-24         2    5960.0      5960
1151385      오리온촉촉초코칩  2022-02-02         2    5960.0      5960
1151392      오리온촉촉초코칩  2022-02-09         2    5960.0      5960
482240    롯데빼빼로3번들꼬아크  2021-09-18         2    5960.0      5960
482239    롯데빼빼로3번들꼬아크  2021-09-17         2    5960.0      5960
482237    롯데빼빼로3번들꼬아크  2021-09-15         2    5960.0      5960
482236    롯데빼빼로3번들꼬아크  2021-09-14         2    5960.0      5960

In [8]:
df.sort_values('SALE_QTY', ascending=False).head(50)

                GDS_NM      SAL_DT  SALE_QTY   SALE_PRC    SALE_AMT
951798          아이스콘1개  2021-11-06     10999     1800.0     9899100
173047        국순당대박막걸리  2021-09-19     10003     4000.0    10003000
1234603             잡화  2021-11-06     10003   407900.0 -2147475748
1268064          종이컵박스  2021-09-19     10000    19800.0    99000000
875599          소금20kg  2021-09-19      9999    27000.0   269973000
847179         서울우유18ℓ  2021-11-26      9001    11600.0    52205800
657780             배송비  2022-03-04      8000        4.0        8000
952159       아이스크림바10개  2022-06-18      7962     2000.0     3981000
297518            달래1단  2022-02-10      7414    69000.0     7414000
701981            베지밀B  2021-10-31      7258    32900.0   107406900
939513        쓰레기봉투50L  2021-10-06      7075     6160.0    10895500
865364      성경구운김밥김10매  2021-10-15      5001     4100.0    10252050
877666            소주공병  2022-01-25      4968     3600.0      496800
644096         밀대청소기리필  2021-09-09      4082     7400.0    15103400
970497              야채  2021-11-07      3977   168000.0     9929000
130787           강쇠동동주  2021-11-26      3606     3500.0     4326900
1013561     오뚜기3분쇠고기카레  2022-02-17      3061     3480.0     3642500
849398           서울우유소  2021-10-02      3005     3000.0     3005000
929024            쌀소성주  2021-10-15      2798    56250.0     3497500
1186369   요리가맛있는당면500g  2021-10-18      2723     6300.0     5718300
1265516          종량20L  2022-03-20      2536    23650.0     1098650
1242738         점보젤리풍선  2022-06-11      2501     5000.0     6252500
597381    맥심모카골드리필170g  2021-11-26      2401    17000.0    20408500
455728        롯데국산햄로스팜  2022-02-17      2295     1600.0     3672000
1013202     오뚜기3분쇠고기짜장  2021-12-21      2237     8100.0     2237600
1394209        청정원한우곰탕  2021-12-21      2236     7220.0     2459120
1013516     오뚜기3분쇠고기카레  2021-12-21      2233     4100.0     2233100
1571011           펭귄황도  2021-12-21      2233     7550.0     4019750
1570987           펭귄황도  2021-10-13      2192     3950.0     4329200
1013560     오뚜기3분쇠고기카레  2022-02-15      2161     5960.0     2571140
951955       아이스크림바10개  2021-09-23      2109     7600.0      843600
743321        빙그레굿모닝우유  2022-03-10      2097    15050.0     4613050
202382   꿀수박59kg이상1통행사  2022-07-16      2081  1264000.0    32879800
952215       아이스크림바10개  2022-08-13      2039   131340.0     8115220
983029             양파소  2022-04-19      2013    37500.0     5032500
202472             꿀젤리  2022-03-07      2006    13000.0     4011000
850699        서울우유커피카톤  2022-01-12      2002     2000.0     2002000
455727        롯데국산햄로스팜  2022-02-15      1617     1600.0     2587200
1013251     오뚜기3분쇠고기짜장  2022-02-17      1542     7200.0     1543300
412596          동원참치기획  2022-02-17      1530     1700.0     2601000
1571039           펭귄황도  2022-02-17      1530     1500.0     2295000
811463              상추  2022-08-01      1506    20300.0     4367400
182969           기내도시락  2022-03-29      1501     3000.0     2251500
455720        롯데국산햄로스팜  2022-01-25      1404     1600.0     2246400
1013545     오뚜기3분쇠고기카레  2022-01-28      1360     3800.0     1292000
692866           백오이3개  2022-05-30      1309   187000.0     1309000
1312125      참이슬클래식18L  2022-08-05      1201    16200.0     6485400
1222264      인큐애호박2개행사  2022-03-01      1188   673000.0     1188000
265324        농심짜파게티멀티  2021-12-21      1137   112740.0     5215230
877681            소주공병  2022-02-22      1129     4680.0      109300

In [9]:
df['GDS_NM'].value_counts()

남양프로바이오틱포도      366
흙당근             366
남양맛있는우유GT기획     366
청경채             366
인큐애호박           366
               ...
맛간장국찌개용930ml      1
데톨핸드오리지날          1
금강양은냄비            1
프레고소시지앤갈릭         1
튀김전용유18L          1
Name: GDS_NM, Length: 22576, dtype: int64

In [10]:
df.to_csv('df21011_3.csv', index=False)

In [11]:
df

                GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1                 0000  2021-09-28         3    1800.0      5400
15                0000  2022-05-26         2    3600.0      3600
19                0000  2022-07-28         2    1800.0      3600
21                0000  2022-08-14         2    1800.0      3600
23       0241405572666  2022-06-22         2     900.0      1800
...                ...         ...       ...       ...       ...
1776816       히츨러수수깡캔디  2021-09-01         2    7000.0      7000
1776817       히츨러수수깡캔디  2021-09-06         2    7000.0      7000
1776825       히츨러수수깡캔디  2021-09-26         2    7000.0      7000
1776828       히츨러수수깡캔디  2021-12-03         2    3500.0      7000
1776829       히츨러수수깡캔디  2021-12-04         2    3500.0      7000

[943752 rows x 5 columns]

In [18]:
df['SALE_QTY'].max()

10999

In [19]:
df['SALE_QTY'].min()

3

In [13]:
df['SALE_QTY'].mean()

8.113217243513127

In [15]:
df['SALE_QTY'].median()

3.0

In [16]:
df = df[df.SALE_QTY > 2]

In [17]:
df

              GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1               0000  2021-09-28         3    1800.0      5400
37       10001200청량초  2021-11-13         5    3000.0      5000
38       10001200청량초  2021-11-14         3    2000.0      3000
39       10001200청량초  2021-11-18         3    2000.0      3000
65       10001200청량초  2022-03-20         3    1000.0      3000
...              ...         ...       ...       ...       ...
1776773       히츠퍼플라벨  2022-07-26         4    9000.0     18000
1776775       히츠퍼플라벨  2022-07-30         4    9000.0     18000
1776783       히츠퍼플라벨  2022-08-09         4    9000.0     18000
1776793       히츠퍼플라벨  2022-08-23         4    9000.0     18000
1776796       히츠퍼플라벨  2022-08-26         3    9000.0     13500

[609070 rows x 5 columns]

In [23]:
df['GDS_NM'] = df['GDS_NM'].str.replace(r'[0-9]+', repl=r'')

<ipython-input-23-d66f946a4fd9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GDS_NM'] = df['GDS_NM'].str.replace(r'[0-9]+', repl=r'')

In [24]:
df

         GDS_NM      SAL_DT  SALE_QTY  SALE_PRC  SALE_AMT
1                2021-09-28         3    1800.0      5400
37          청량초  2021-11-13         5    3000.0      5000
38          청량초  2021-11-14         3    2000.0      3000
39          청량초  2021-11-18         3    2000.0      3000
65          청량초  2022-03-20         3    1000.0      3000
...         ...         ...       ...       ...       ...
1776773  히츠퍼플라벨  2022-07-26         4    9000.0     18000
1776775  히츠퍼플라벨  2022-07-30         4    9000.0     18000
1776783  히츠퍼플라벨  2022-08-09         4    9000.0     18000
1776793  히츠퍼플라벨  2022-08-23         4    9000.0     18000
1776796  히츠퍼플라벨  2022-08-26         3    9000.0     13500

[609070 rows x 5 columns]

In [25]:
df.to_csv('df21011_4.csv', index=False)