In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''

In [2]:
df = pd.read_csv(base_path + 'df1005.csv')
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,3
1,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,5
2,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,5
3,2021-05-30,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,6
4,2021-05-31,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9556486800210,망고푸딩,1.0,3500.0,3500.0,8,5
23660708,2022-08-28,9556486800210,망고푸딩,1.0,3500.0,3500.0,8,6
23660709,2022-09-13,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,1
23660710,2022-09-20,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,1
23660711,2022-09-22,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,3

In [3]:
df = df.astype({'SALE_AMT' : 'int'})

In [4]:
test = df.sort_values('SALE_QTY', ascending=False).head(50)
test

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
840608,2022-01-24,8801045299419,오옛날사골곰탕,9999.0,1000.0,9999000,1,0
23272520,2021-09-19,2501130000710,소금20kg,9999.0,27000.0,269973000,9,6
5867762,2022-04-02,200131,모듬쌈채류,9999.0,170210.0,1701929790,4,5
9093548,2022-04-21,8809517210078,에그탑특란,9999.0,10000.0,79792020,4,3
23304225,2021-11-06,2599990000117,잡화,9999.0,400000.0,-2147483648,11,5
6172715,2022-01-14,22001566,츄파춥스,9999.0,250.0,2499750,1,4
23303810,2021-11-06,2599990000100,아이스콘1개,9999.0,900.0,8999100,11,5
7625845,2022-03-17,202024,딸기,9999.0,10000.0,99990000,3,3
23508536,2021-09-19,8802521125819,국순당대박막걸리,9999.0,1000.0,9999000,9,6
5867761,2022-04-02,200131,모듬쌈채류,9999.0,172720.0,1727027280,4,5
23545475,2021-09-19,8809440820009,종이컵박스,9999.0,9900.0,98990100,9,6
6565460,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999.0,3900.0,38996100,5,1
5874085,2022-01-14,200160,백오이,9999.0,2480.0,24797520,1,4
19644872,2021-04-03,8801048101023,진로이즈백,9982.0,1350.0,13475700,4,5
14013288,2022-05-23,22000539,제스프리,9800.0,5000.0,49000000,5,0
14031237,2021-10-20,2999000001064,천하장사,9800.0,200.0,1960000,10,2
11979951,2022-06-02,2900000000322,공산,9650.0,4000.0,38600000,6,3
6402399,2022-07-04,8801013113136,큐원하얀설탕,9000.0,11500.0,85320000,7,0
5867760,2022-04-02,200131,모듬쌈채류,9000.0,176650.0,1589850000,4,5
6333793,2022-07-04,8801007227320,CJ백설하얀설탕,9000.0,12000.0,71820000,7,0
13133684,2021-11-26,2489898982335,흙대파,9000.0,990.0,8910000,11,4
13133711,2021-11-30,2489898982335,흙대파,9000.0,990.0,8910000,11,1
6402420,2022-07-04,8801013120479,큐원갈색설탕,9000.0,12500.0,99000000,7,0
6326358,2022-07-04,8801007144641,CJ갈색설탕,9000.0,14500.0,89100000,7,0
23439332,2021-11-26,8801115111030,서울우유18ℓ,9000.0,5800.0,52200000,11,4
11978289,2021-11-12,2900000000025,청과,8900.0,1000.0,8900000,11,4
10010553,2021-07-12,8801115111030,서울우유18,8888.0,5000.0,44440000,7,0
11841198,2022-06-18,8809246700048,강릉최가심층수두부,8855.0,2980.0,17532900,6,5
1058592,2021-10-25,8801056175870,롯데펩시콜라제로250,8801.0,750.0,6600750,10,0
13441078,2022-04-11,8806006508227,유한락스후로랄1L12,8076.0,3100.0,25035600,4,0
10508464,2022-03-25,2002033,한라봉,7900.0,7900.0,62410000,3,4
13311146,2022-03-02,8801094012502,코카콜라2L,7889.0,3400.0,26822600,3,2
13311145,2022-03-02,8801094012502,코카콜라2L,7889.0,3400.0,26822600,3,2
14013291,2022-05-24,22000539,제스프리,7723.0,6800.0,52516400,5,1
14013344,2022-06-13,22000539,제스프리,7723.0,11400.0,88042200,6,0
14013127,2022-03-09,22000539,제스프리,7723.0,9800.0,75685400,3,2
14013365,2022-07-06,22000539,제스프리,7723.0,6000.0,46338000,7,2
14013369,2022-07-19,22000539,제스프리,7723.0,5700.0,44021100,7,1
14013165,2022-03-22,22000539,제스프리,7723.0,9800.0,75685400,3,1
16772399,2020-12-20,2909441428986,가지고추1팩,7333.0,2500.0,18332500,12,6
18629944,2021-10-31,8801033786259,베지밀B,7256.0,14800.0,107388800,10,6
4355362,2022-03-03,22002853,스치딸기1kg행사,7020.0,14800.0,89856000,3,3
12973136,2022-03-06,8802272111260,일판특란30구,6900.0,6980.0,48162000,3,6
11979948,2022-06-01,2900000000322,공산,6800.0,4000.0,27200000,6,2
14107902,2021-12-16,8801052801773,청정원현미찰고추장사각,6800.0,3300.0,22440000,12,3
11979947,2022-06-01,2900000000322,공산,6800.0,4000.0,27200000,6,2
11754160,2021-10-20,8801117149109,오예감실속형기획,6662.0,4980.0,26514760,10,2
15897889,2022-02-10,2908990006065,달래1단,6662.0,1000.0,6662000,2,3
13753097,2022-06-23,8801062713431,롯데아이러브토스트대,6629.0,3000.0,19887000,6,3
4407169,2022-01-04,22005137,개구리호박둥근호박,6536.0,1980.0,12941280,1,1

In [5]:
test1 = df.sort_values('SALE_AMT', ascending=False).head(50)
test1

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
13953223,2022-03-23,201044,딸기,2.0,880491120.0,1760982240,3,2
5867761,2022-04-02,200131,모듬쌈채류,9999.0,172720.0,1727027280,4,5
5867762,2022-04-02,200131,모듬쌈채류,9999.0,170210.0,1701929790,4,5
5867760,2022-04-02,200131,모듬쌈채류,9000.0,176650.0,1589850000,4,5
2663438,2021-09-26,520000009,망고스틴,1.0,941181000.0,941181000,9,6
2086866,2022-02-10,200000,청량고추,1.0,930144000.0,930144000,2,3
2326423,2022-01-10,22000033,식품,3000.0,300000.0,900000000,1,0
77228,2021-10-18,200047,청상추1봉,1.0,880306000.0,880306000,10,0
985165,2022-08-13,8801051088151,엘자연퐁용기베이킹소다레몬,1.0,880109440.0,880109440,8,5
1074764,2022-07-22,8801056227708,롯데칠성사이다플러스500ml,1.0,880104890.0,880104890,7,4
10730020,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
10730019,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
10730018,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
5617987,2021-08-30,8809102740386,왕란,3.0,288090720.0,864272160,8,0
11065601,2022-04-07,8801118256790,델몬트미니컵홈,1.0,600012450.0,600012450,4,3
12600607,2022-04-05,2734840004703,배선물세트9과,1.0,590020000.0,590020000,4,1
2086865,2021-12-13,200000,청량고추,1.0,518831980.0,518831980,12,0
11274005,2022-09-01,200000,다시마,1.0,490603600.0,490603600,9,3
10990643,2021-08-15,8801115114383,서울우유3651등급우유,2.0,200113900.0,400227800,8,6
12581799,2021-09-18,2734840001641,햇망양파3kg,2.0,200025400.0,400050800,9,5
14031799,2022-08-16,3800111203089,크랄스카레몬보드카,1.0,380011120.0,380011120,8,1
17435823,2021-10-10,351030,국내산돈가브리살,1.0,351028000.0,351028000,10,6
15656019,2022-02-19,2908990004702,쥬키니호박2개,1.0,351010010.0,351010010,2,5
17239005,2022-04-11,351001,국내산돈삼겹살,1.0,351008000.0,351008000,4,0
281922,2022-05-20,211023,식품,1.0,292222000.0,292222000,5,4
11836873,2022-08-20,8809182054694,자연담은쌀21년산햅쌀,5940.0,68000.0,285120000,8,5
12542057,2022-04-20,2000804,천혜향,1.0,279002000.0,279002000,4,2
23272520,2021-09-19,2501130000710,소금20kg,9999.0,27000.0,269973000,9,6
10548340,2022-01-07,255341,생삼겹살구이용,1.0,255103000.0,229592700,1,4
12615352,2022-09-08,290009,과자,1.0,220000570.0,220000570,9,3
13120087,2022-06-06,218100,대패삼겹살수입산,1.0,218231000.0,218231000,6,0
7612764,2021-12-18,201352,섬초,1.0,205356010.0,205356010,12,5
7807807,2021-10-02,22002693,자두,1.0,205260010.0,205260010,10,5
10556480,2021-08-11,2907062812320,건어물,1.0,205203010.0,205203010,8,2
7607424,2022-08-16,201344,흙당근,1.0,205168010.0,205168010,8,1
7595583,2022-05-06,201321,표고버섯국산,1.0,205045000.0,205045000,5,4
7550736,2021-10-24,201176,생강,1.0,205028000.0,205028000,10,6
7589290,2022-09-04,201280,청양고추,1.0,204503000.0,204503000,9,6
7516869,2022-04-01,201004,감자,1.0,204503000.0,204503000,4,4
2475682,2022-06-06,22002662,청과류,1.0,204334000.0,204334000,6,0
7163481,2021-10-04,8801492361608,하림닭볶음탕용900g,1.0,204304000.0,204304000,10,0
4460081,2022-08-22,22007711,델몬트바나나,1.0,204240010.0,204240010,8,0
4301918,2021-09-01,22001665,무우소,1.0,204186020.0,204186020,9,2
4488092,2021-09-25,22010339,노각오이,1.0,204173020.0,204173020,9,5
4094788,2022-09-30,201344,흙당근,1.0,204173000.0,204173000,9,4
4108959,2022-02-12,201443,밤고구마행사,1.0,204126000.0,204126000,2,5
7517380,2022-04-18,201004,감자,1.0,204012000.0,204012000,4,0
4497562,2022-08-29,22010704,청양고추300g,1.0,203259010.0,203259010,8,0
4037071,2021-11-13,201153,봄동,1.0,203170000.0,203170000,11,5
4469928,2022-05-05,22008633,딸기1팩35,1.0,203118010.0,203118010,5,3

In [6]:
test2 = df.sort_values('SALE_AMT', ascending=True).head(50)
test2

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
23304225,2021-11-06,2599990000117,잡화,9999.0,400000.0,-2147483648,11,5
2084302,2021-09-01,2,사은행사쿠폰,1.0,-5000.0,-5000,9,2
5829710,2021-09-02,2,사은행사쿠폰,1.0,-5000.0,-5000,9,3
5829711,2021-09-02,2,사은행사쿠폰,1.0,-5000.0,-5000,9,3
5829837,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5829712,2021-09-02,2,사은행사쿠폰,1.0,-5000.0,-5000,9,3
5829713,2021-09-02,2,사은행사쿠폰,1.0,-5000.0,-5000,9,3
2084291,2021-09-01,2,사은행사쿠폰,1.0,-5000.0,-5000,9,2
5829835,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
10388469,2021-09-25,2,벌집삼겹살500g국내산,1.0,-5000.0,-5000,9,5
2084858,2021-09-14,2,사은행사쿠폰,1.0,-5000.0,-5000,9,1
10388468,2021-09-23,2,벌집삼겹살500g국내산,1.0,-5000.0,-5000,9,3
7504076,2021-08-28,2,사은행사쿠폰,1.0,-5000.0,-5000,8,5
5829716,2021-09-04,2,사은행사쿠폰,1.0,-5000.0,-5000,9,5
10388467,2021-09-23,2,벌집삼겹살500g국내산,1.0,-5000.0,-5000,9,3
2085142,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
2084855,2021-09-14,2,사은행사쿠폰,1.0,-5000.0,-5000,9,1
2085143,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829787,2021-09-10,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829786,2021-09-10,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
2085145,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829784,2021-09-10,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
2085147,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
2084202,2021-08-28,2,사은행사쿠폰,1.0,-5000.0,-5000,8,5
2084203,2021-08-28,2,사은행사쿠폰,1.0,-5000.0,-5000,8,5
5829782,2021-09-10,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829838,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5829781,2021-09-10,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
2085141,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
10388470,2021-09-25,2,벌집삼겹살500g국내산,1.0,-5000.0,-5000,9,5
2084227,2021-08-30,2,사은행사쿠폰,1.0,-5000.0,-5000,8,0
5829849,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5829848,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5829847,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5830049,2021-09-28,2,사은행사쿠폰,1.0,-5000.0,-5000,9,1
5829846,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
5829845,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
2085133,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829844,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
2084255,2021-08-31,2,사은행사쿠폰,1.0,-5000.0,-5000,8,1
2085135,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4
5829843,2021-09-12,2,사은행사쿠폰,1.0,-5000.0,-5000,9,6
2084465,2021-09-06,2,사은행사쿠폰,1.0,-5000.0,-5000,9,0
2084696,2021-09-11,2,사은행사쿠폰,1.0,-5000.0,-5000,9,5
2084867,2021-09-14,2,사은행사쿠폰,1.0,-5000.0,-5000,9,1
2084698,2021-09-11,2,사은행사쿠폰,1.0,-5000.0,-5000,9,5
10388471,2021-09-26,2,벌집삼겹살500g국내산,1.0,-5000.0,-5000,9,6
5830052,2021-09-28,2,사은행사쿠폰,1.0,-5000.0,-5000,9,1
5829708,2021-09-02,2,사은행사쿠폰,1.0,-5000.0,-5000,9,3
2085138,2021-09-24,2,사은행사쿠폰,1.0,-5000.0,-5000,9,4

In [8]:
test3 = df.sort_values('SALE_PRC', ascending=False).head(100)
test3

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
2663438,2021-09-26,520000009,망고스틴,1.0,941181000.0,941181000,9,6
2086866,2022-02-10,200000,청량고추,1.0,930144000.0,930144000,2,3
13953223,2022-03-23,201044,딸기,2.0,880491120.0,1760982240,3,2
77228,2021-10-18,200047,청상추1봉,1.0,880306000.0,880306000,10,0
985165,2022-08-13,8801051088151,엘자연퐁용기베이킹소다레몬,1.0,880109440.0,880109440,8,5
...,...,...,...,...,...,...,...,...
292072,2022-04-23,211027,야채,1.0,8588500.0,8588500,4,5
282157,2022-07-16,211023,식품,1.0,7217000.0,7217000,7,5
5838734,2022-07-22,200049,햇감자,1.0,7027370.0,7027370,7,4
5838735,2022-07-22,200049,햇감자,1.0,7027370.0,7027370,7,4
12618627,2022-03-25,290016,잡화,1.0,6427300.0,6427300,3,4

In [4]:
df['SALE_QTY'].value_counts()

1.0       20058595
2.0        2501029
3.0         512049
4.0         232075
5.0         124753
            ...
730.0            1
2960.0           1
2700.0           1
5450.0           1
3600.0           1
Name: SALE_QTY, Length: 427, dtype: int64

In [7]:
test

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
840608,2022-01-24,8801045299419,오옛날사골곰탕,9999.0,1000.0,9.999000e+06,1,0
23272520,2021-09-19,2501130000710,소금20kg,9999.0,27000.0,2.699730e+08,9,6
5867762,2022-04-02,200131,모듬쌈채류,9999.0,170210.0,1.701930e+09,4,5
9093548,2022-04-21,8809517210078,에그탑특란,9999.0,10000.0,7.979202e+07,4,3
23304225,2021-11-06,2599990000117,잡화,9999.0,400000.0,3.999600e+09,11,5
6172715,2022-01-14,22001566,츄파춥스,9999.0,250.0,2.499750e+06,1,4
23303810,2021-11-06,2599990000100,아이스콘1개,9999.0,900.0,8.999100e+06,11,5
7625845,2022-03-17,202024,딸기,9999.0,10000.0,9.999000e+07,3,3
23508536,2021-09-19,8802521125819,국순당대박막걸리,9999.0,1000.0,9.999000e+06,9,6
5867761,2022-04-02,200131,모듬쌈채류,9999.0,172720.0,1.727027e+09,4,5
23545475,2021-09-19,8809440820009,종이컵박스,9999.0,9900.0,9.899010e+07,9,6
6565460,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999.0,3900.0,3.899610e+07,5,1
5874085,2022-01-14,200160,백오이,9999.0,2480.0,2.479752e+07,1,4
19644872,2021-04-03,8801048101023,진로이즈백,9982.0,1350.0,1.347570e+07,4,5
14013288,2022-05-23,22000539,제스프리,9800.0,5000.0,4.900000e+07,5,0
14031237,2021-10-20,2999000001064,천하장사,9800.0,200.0,1.960000e+06,10,2
11979951,2022-06-02,2900000000322,공산,9650.0,4000.0,3.860000e+07,6,3
6402399,2022-07-04,8801013113136,큐원하얀설탕,9000.0,11500.0,8.532000e+07,7,0
5867760,2022-04-02,200131,모듬쌈채류,9000.0,176650.0,1.589850e+09,4,5
6333793,2022-07-04,8801007227320,CJ백설하얀설탕,9000.0,12000.0,7.182000e+07,7,0
13133684,2021-11-26,2489898982335,흙대파,9000.0,990.0,8.910000e+06,11,4
13133711,2021-11-30,2489898982335,흙대파,9000.0,990.0,8.910000e+06,11,1
6402420,2022-07-04,8801013120479,큐원갈색설탕,9000.0,12500.0,9.900000e+07,7,0
6326358,2022-07-04,8801007144641,CJ갈색설탕,9000.0,14500.0,8.910000e+07,7,0
23439332,2021-11-26,8801115111030,서울우유18ℓ,9000.0,5800.0,5.220000e+07,11,4
11978289,2021-11-12,2900000000025,청과,8900.0,1000.0,8.900000e+06,11,4
10010553,2021-07-12,8801115111030,서울우유18,8888.0,5000.0,4.444000e+07,7,0
11841198,2022-06-18,8809246700048,강릉최가심층수두부,8855.0,2980.0,1.753290e+07,6,5
1058592,2021-10-25,8801056175870,롯데펩시콜라제로250,8801.0,750.0,6.600750e+06,10,0
13441078,2022-04-11,8806006508227,유한락스후로랄1L12,8076.0,3100.0,2.503560e+07,4,0
10508464,2022-03-25,2002033,한라봉,7900.0,7900.0,6.241000e+07,3,4
13311146,2022-03-02,8801094012502,코카콜라2L,7889.0,3400.0,2.682260e+07,3,2
13311145,2022-03-02,8801094012502,코카콜라2L,7889.0,3400.0,2.682260e+07,3,2
14013291,2022-05-24,22000539,제스프리,7723.0,6800.0,5.251640e+07,5,1
14013344,2022-06-13,22000539,제스프리,7723.0,11400.0,8.804220e+07,6,0
14013127,2022-03-09,22000539,제스프리,7723.0,9800.0,7.568540e+07,3,2
14013365,2022-07-06,22000539,제스프리,7723.0,6000.0,4.633800e+07,7,2
14013369,2022-07-19,22000539,제스프리,7723.0,5700.0,4.402110e+07,7,1
14013165,2022-03-22,22000539,제스프리,7723.0,9800.0,7.568540e+07,3,1
16772399,2020-12-20,2909441428986,가지고추1팩,7333.0,2500.0,1.833250e+07,12,6
18629944,2021-10-31,8801033786259,베지밀B,7256.0,14800.0,1.073888e+08,10,6
4355362,2022-03-03,22002853,스치딸기1kg행사,7020.0,14800.0,8.985600e+07,3,3
12973136,2022-03-06,8802272111260,일판특란30구,6900.0,6980.0,4.816200e+07,3,6
11979948,2022-06-01,2900000000322,공산,6800.0,4000.0,2.720000e+07,6,2
14107902,2021-12-16,8801052801773,청정원현미찰고추장사각,6800.0,3300.0,2.244000e+07,12,3
11979947,2022-06-01,2900000000322,공산,6800.0,4000.0,2.720000e+07,6,2
11754160,2021-10-20,8801117149109,오예감실속형기획,6662.0,4980.0,2.651476e+07,10,2
15897889,2022-02-10,2908990006065,달래1단,6662.0,1000.0,6.662000e+06,2,3
13753097,2022-06-23,8801062713431,롯데아이러브토스트대,6629.0,3000.0,1.988700e+07,6,3
4407169,2022-01-04,22005137,개구리호박둥근호박,6536.0,1980.0,1.294128e+07,1,1

In [9]:
df.sort_values('SALE_QTY', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
840608,2022-01-24,8801045299419,오옛날사골곰탕,9999.0,1000.0,9.999000e+06,1,0
23272520,2021-09-19,2501130000710,소금20kg,9999.0,27000.0,2.699730e+08,9,6
5867762,2022-04-02,200131,모듬쌈채류,9999.0,170210.0,1.701930e+09,4,5
9093548,2022-04-21,8809517210078,에그탑특란,9999.0,10000.0,7.979202e+07,4,3
23304225,2021-11-06,2599990000117,잡화,9999.0,400000.0,3.999600e+09,11,5
...,...,...,...,...,...,...,...,...
3664135,2021-12-17,8801155978136,동원소와나무고칼슘우유,0.0,4800.0,0.000000e+00,12,4
5942546,2021-09-16,201034,한우양지국거리,0.0,5500.0,0.000000e+00,9,3
5977449,2021-11-20,201231,도드람한돈생목살구이,0.0,11500.0,0.000000e+00,11,5
5942548,2021-09-16,201034,한우양지국거리,0.0,5500.0,0.000000e+00,9,3
2216148,2022-01-06,204229,한돈암돼지생삼겹살,0.0,15800.0,0.000000e+00,1,3

In [10]:
df = df.astype({'SALE_QTY' : 'int'})

In [11]:
df = df.astype({'SALE_AMT' : 'int'})

In [12]:
df.sort_values('SALE_QTY', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
840608,2022-01-24,8801045299419,오옛날사골곰탕,9999,1000.0,9999000,1,0
23272520,2021-09-19,2501130000710,소금20kg,9999,27000.0,269973000,9,6
5867762,2022-04-02,200131,모듬쌈채류,9999,170210.0,1701929790,4,5
9093548,2022-04-21,8809517210078,에그탑특란,9999,10000.0,79792020,4,3
23304225,2021-11-06,2599990000117,잡화,9999,400000.0,-2147483648,11,5
...,...,...,...,...,...,...,...,...
3664135,2021-12-17,8801155978136,동원소와나무고칼슘우유,0,4800.0,0,12,4
5942546,2021-09-16,201034,한우양지국거리,0,5500.0,0,9,3
5977449,2021-11-20,201231,도드람한돈생목살구이,0,11500.0,0,11,5
5942548,2021-09-16,201034,한우양지국거리,0,5500.0,0,9,3
2216148,2022-01-06,204229,한돈암돼지생삼겹살,0,15800.0,0,1,3

In [13]:
df.sort_values('SALE_QTY', ascending=False).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
840608,2022-01-24,8801045299419,오옛날사골곰탕,9999,1000.0,9999000,1,0
23272520,2021-09-19,2501130000710,소금20kg,9999,27000.0,269973000,9,6
5867762,2022-04-02,200131,모듬쌈채류,9999,170210.0,1701929790,4,5
9093548,2022-04-21,8809517210078,에그탑특란,9999,10000.0,79792020,4,3
23304225,2021-11-06,2599990000117,잡화,9999,400000.0,-2147483648,11,5
6172715,2022-01-14,22001566,츄파춥스,9999,250.0,2499750,1,4
23303810,2021-11-06,2599990000100,아이스콘1개,9999,900.0,8999100,11,5
7625845,2022-03-17,202024,딸기,9999,10000.0,99990000,3,3
23508536,2021-09-19,8802521125819,국순당대박막걸리,9999,1000.0,9999000,9,6
5867761,2022-04-02,200131,모듬쌈채류,9999,172720.0,1727027280,4,5
23545475,2021-09-19,8809440820009,종이컵박스,9999,9900.0,98990100,9,6
6565460,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999,3900.0,38996100,5,1
5874085,2022-01-14,200160,백오이,9999,2480.0,24797520,1,4
19644872,2021-04-03,8801048101023,진로이즈백,9982,1350.0,13475700,4,5
14013288,2022-05-23,22000539,제스프리,9800,5000.0,49000000,5,0
14031237,2021-10-20,2999000001064,천하장사,9800,200.0,1960000,10,2
11979951,2022-06-02,2900000000322,공산,9650,4000.0,38600000,6,3
6402399,2022-07-04,8801013113136,큐원하얀설탕,9000,11500.0,85320000,7,0
5867760,2022-04-02,200131,모듬쌈채류,9000,176650.0,1589850000,4,5
6333793,2022-07-04,8801007227320,CJ백설하얀설탕,9000,12000.0,71820000,7,0
13133684,2021-11-26,2489898982335,흙대파,9000,990.0,8910000,11,4
13133711,2021-11-30,2489898982335,흙대파,9000,990.0,8910000,11,1
6402420,2022-07-04,8801013120479,큐원갈색설탕,9000,12500.0,99000000,7,0
6326358,2022-07-04,8801007144641,CJ갈색설탕,9000,14500.0,89100000,7,0
23439332,2021-11-26,8801115111030,서울우유18ℓ,9000,5800.0,52200000,11,4
11978289,2021-11-12,2900000000025,청과,8900,1000.0,8900000,11,4
10010553,2021-07-12,8801115111030,서울우유18,8888,5000.0,44440000,7,0
11841198,2022-06-18,8809246700048,강릉최가심층수두부,8855,2980.0,17532900,6,5
1058592,2021-10-25,8801056175870,롯데펩시콜라제로250,8801,750.0,6600750,10,0
13441078,2022-04-11,8806006508227,유한락스후로랄1L12,8076,3100.0,25035600,4,0
10508464,2022-03-25,2002033,한라봉,7900,7900.0,62410000,3,4
13311146,2022-03-02,8801094012502,코카콜라2L,7889,3400.0,26822600,3,2
13311145,2022-03-02,8801094012502,코카콜라2L,7889,3400.0,26822600,3,2
14013291,2022-05-24,22000539,제스프리,7723,6800.0,52516400,5,1
14013344,2022-06-13,22000539,제스프리,7723,11400.0,88042200,6,0
14013127,2022-03-09,22000539,제스프리,7723,9800.0,75685400,3,2
14013365,2022-07-06,22000539,제스프리,7723,6000.0,46338000,7,2
14013369,2022-07-19,22000539,제스프리,7723,5700.0,44021100,7,1
14013165,2022-03-22,22000539,제스프리,7723,9800.0,75685400,3,1
16772399,2020-12-20,2909441428986,가지고추1팩,7333,2500.0,18332500,12,6
18629944,2021-10-31,8801033786259,베지밀B,7256,14800.0,107388800,10,6
4355362,2022-03-03,22002853,스치딸기1kg행사,7020,14800.0,89856000,3,3
12973136,2022-03-06,8802272111260,일판특란30구,6900,6980.0,48162000,3,6
11979948,2022-06-01,2900000000322,공산,6800,4000.0,27200000,6,2
14107902,2021-12-16,8801052801773,청정원현미찰고추장사각,6800,3300.0,22440000,12,3
11979947,2022-06-01,2900000000322,공산,6800,4000.0,27200000,6,2
11754160,2021-10-20,8801117149109,오예감실속형기획,6662,4980.0,26514760,10,2
15897889,2022-02-10,2908990006065,달래1단,6662,1000.0,6662000,2,3
13753097,2022-06-23,8801062713431,롯데아이러브토스트대,6629,3000.0,19887000,6,3
4407169,2022-01-04,22005137,개구리호박둥근호박,6536,1980.0,12941280,1,1

In [14]:
df.sort_values('SALE_QTY', ascending=True).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
5992873,2022-07-30,201238,한돈생칼집삼겹살,0,10950.0,0,7,5
5144803,2022-07-09,8801069173603,남양맛있는우유GT,0,2600.0,0,7,5
12051345,2022-02-22,8801037088168,오레오화이트크림소,0,1450.0,0,2,1
3434451,2022-02-19,8801111770217,크라운야채타임,0,1200.0,0,2,5
5953008,2021-10-25,201048,한우다짐육1,0,4300.0,0,10,0
5953010,2021-10-25,201048,한우다짐육1,0,4300.0,0,10,0
11362497,2022-08-04,201163,햇배추낱개,0,5800.0,0,8,3
11362496,2022-08-04,201163,햇배추낱개,0,5800.0,0,8,3
9889518,2022-06-28,8801068402247,삼립다그다딸기카스타드빵,0,1500.0,0,6,1
10921073,2021-12-25,8801094749491,코카콜라암바사,0,3980.0,0,12,5
2122241,2022-02-13,201153,봄동,0,450.0,0,2,6
5953017,2021-10-26,201048,한우다짐육1,0,4300.0,0,10,1
3645538,2021-12-05,8801155730932,동원덴마크산양우유,0,4950.0,0,12,6
5953019,2021-10-26,201048,한우다짐육1,0,4300.0,0,10,1
2711645,2022-03-07,8801005182164,샘표양념이듬뿍맛있는쌈장,0,3500.0,0,3,0
2711646,2022-03-07,8801005182164,샘표양념이듬뿍맛있는쌈장,0,3500.0,0,3,0
2122244,2022-02-13,201153,봄동,0,450.0,0,2,6
6299907,2022-07-10,8801005960137,샘표폰타나베이컨머쉬룸크림파스타소스,0,6550.0,0,7,6
6299908,2022-07-10,8801005960137,샘표폰타나베이컨머쉬룸크림파스타소스,0,6550.0,0,7,6
17829306,2022-03-28,8436036186227,트롤리샤워구미믹스B,0,2200.0,0,3,0
17829307,2022-03-28,8436036186227,트롤리샤워구미믹스B,0,2200.0,0,3,0
3763170,2021-09-12,8803712128008,목우촌김밥햄,0,3100.0,0,9,6
3763169,2021-09-12,8803712128008,목우촌김밥햄,0,3100.0,0,9,6
11827215,2022-01-29,8808244208044,광동삼다수2L6입,0,9500.0,0,1,5
6250277,2022-09-29,2200408605182,포켓몬빵1가구2개한정,0,1500.0,0,9,3
6250278,2022-09-29,2200408605182,포켓몬빵1가구2개한정,0,1500.0,0,9,3
7337183,2022-03-21,8809180744047,잘풀리는집각티슈,0,5900.0,0,3,0
3039940,2022-03-03,8801047169420,양반통참치부대찌개,0,4800.0,0,3,3
3120645,2022-05-11,8801052103310,청정원감칠맛미원,0,3450.0,0,5,2
9889573,2022-06-02,8801068402254,삼립파이리핫소스팡,0,1500.0,0,6,3
12051315,2021-12-24,8801037088168,오레오화이트크림소,0,1300.0,0,12,4
3039971,2021-09-12,8801047169444,동원양반참치김치찌개,0,4800.0,0,9,6
17119355,2022-03-15,2999000002771,물미역1팩,0,800.0,0,3,1
13280344,2022-02-19,8801062634354,롯데아몬드초코볼,0,2400.0,0,2,5
3763236,2021-11-08,8803712128008,목우촌김밥햄,0,3100.0,0,11,0
15013679,2022-06-26,290899000092,블루베리특3팩행사,0,5000.0,0,6,6
2181864,2021-12-31,204016,한우1등급꽃등심,0,25000.0,0,12,4
2181863,2021-12-31,204016,한우1등급꽃등심,0,25000.0,0,12,4
2181861,2021-12-31,204016,한우1등급꽃등심,0,25000.0,0,12,4
11827216,2022-01-29,8808244208044,광동삼다수2L6입,0,9500.0,0,1,5
22767373,2022-07-05,8809219070086,CJ깐메추리알,0,12200.0,0,7,1
17119346,2022-03-14,2999000002771,물미역1팩,0,700.0,0,3,0
17119345,2022-03-14,2999000002771,물미역1팩,0,700.0,0,3,0
6757777,2022-01-08,8801062875702,롯데꼬깔콘찰옥수수맛,0,2500.0,0,1,5
6757778,2022-01-08,8801062875702,롯데꼬깔콘찰옥수수맛,0,2500.0,0,1,5
3277147,2022-08-07,8801068085990,삼립보름달,0,1200.0,0,8,6
5002853,2021-09-09,8801052043517,청정원맛있는비엔나,0,5600.0,0,9,3
16610073,2021-09-09,2909441427255,비포오이1포,0,22800.0,0,9,3
6299877,2022-05-10,8801005960137,샘표폰타나베이컨머쉬룸크림파스타소스,0,6550.0,0,5,1
6299878,2022-05-10,8801005960137,샘표폰타나베이컨머쉬룸크림파스타소스,0,6550.0,0,5,1

In [23]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8801068097474,땅콩샌드,1,1100.0,1100,5,3
1,2021-05-29,8801068097474,땅콩샌드,1,1100.0,1100,5,5
2,2021-05-29,8801068097474,땅콩샌드,1,1100.0,1100,5,5
3,2021-05-30,8801068097474,땅콩샌드,1,1100.0,1100,5,6
4,2021-05-31,8801068097474,땅콩샌드,1,1100.0,1100,5,0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9556486800210,망고푸딩,1,3500.0,3500,8,5
23660708,2022-08-28,9556486800210,망고푸딩,1,3500.0,3500,8,6
23660709,2022-09-13,9556486800210,망고푸딩,1,3500.0,3500,9,1
23660710,2022-09-20,9556486800210,망고푸딩,1,3500.0,3500,9,1
23660711,2022-09-22,9556486800210,망고푸딩,1,3500.0,3500,9,3

In [24]:
df = df.replace(0, np.NaN)

In [25]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,3.0
1,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
2,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
3,2021-05-30,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,6.0
4,2021-05-31,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,NaN
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,5.0
23660708,2022-08-28,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,6.0
23660709,2022-09-13,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660710,2022-09-20,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660711,2022-09-22,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,3.0

In [27]:
df.sort_values('SALE_QTY', ascending=True).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,3.0
15144016,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144015,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144014,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144012,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144011,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144010,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144009,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144018,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144008,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144006,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144005,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144004,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144002,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144001,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144000,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15143999,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144007,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144019,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144020,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144021,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144038,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144037,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144036,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144035,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144034,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144033,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144032,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144031,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144030,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144029,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144028,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144027,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144026,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144025,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144024,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144023,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144022,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15143998,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15144039,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15143997,2021-01-29,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,4.0
15143995,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143971,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143970,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143969,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143968,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143967,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143966,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143965,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0
15143972,2021-01-28,2.908990e+12,쌈배추봉지1통,1.0,1500.0,1500.0,1,3.0

In [28]:
df.isnull().sum()

SAL_DT            0
PLU_CD          405
GDS_NM            0
SALE_QTY      24402
SALE_PRC        314
SALE_AMT      24841
month             0
weekday     3278039
dtype: int64

In [29]:
df = df.dropna(how='any',axis=0)

In [30]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,3.0
1,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
2,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
3,2021-05-30,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,6.0
6,2021-06-01,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,6,1.0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,5.0
23660708,2022-08-28,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,6.0
23660709,2022-09-13,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660710,2022-09-20,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660711,2022-09-22,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,3.0

In [31]:
df.sort_values('SALE_QTY', ascending=True).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,3.0
15184538,2021-07-01,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184539,2021-07-01,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184540,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184541,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184542,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184543,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184544,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184545,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184546,2021-07-02,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,4.0
15184550,2021-07-04,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,6.0
15184551,2021-07-04,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,6.0
15184552,2021-07-04,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,6.0
15184558,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184559,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184560,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184562,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184564,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184579,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184578,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184577,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184576,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184575,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184574,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184537,2021-07-01,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184573,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184571,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184570,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184569,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184568,2021-07-07,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,2.0
15184566,2021-07-07,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,2.0
15184565,2021-07-06,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,1.0
15184572,2021-07-08,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,7,3.0
15184536,2021-06-30,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,2.0
15184535,2021-06-30,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,2.0
15184534,2021-06-30,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,2.0
15184505,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184504,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184503,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184502,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184501,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184500,2021-06-23,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,2.0
15184506,2021-06-24,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,3.0
15184496,2021-06-23,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,2.0
15184493,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0
15184492,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0
15184491,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0
15184490,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0
15184489,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0
15184488,2021-06-22,2.908990e+11,일자콩나물1박스,1.0,2280.0,2280.0,6,1.0

In [32]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,3.0
1,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
2,2021-05-29,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,5.0
3,2021-05-30,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,5,6.0
6,2021-06-01,8.801068e+12,땅콩샌드,1.0,1100.0,1100.0,6,1.0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,5.0
23660708,2022-08-28,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,8,6.0
23660709,2022-09-13,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660710,2022-09-20,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,1.0
23660711,2022-09-22,9.556487e+12,망고푸딩,1.0,3500.0,3500.0,9,3.0