In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''

In [2]:
df = pd.read_csv(base_path + 'df1005.csv')
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,3
1,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,5
2,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,5
3,2021-05-30,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,6
4,2021-05-31,8801068097474,땅콩샌드,1.0,1100.0,1100.0,5,0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9556486800210,망고푸딩,1.0,3500.0,3500.0,8,5
23660708,2022-08-28,9556486800210,망고푸딩,1.0,3500.0,3500.0,8,6
23660709,2022-09-13,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,1
23660710,2022-09-20,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,1
23660711,2022-09-22,9556486800210,망고푸딩,1.0,3500.0,3500.0,9,3

In [3]:
df = df.astype({'SALE_AMT' : 'int'})

In [4]:
q1=df['SALE_AMT'].quantile(0.25)
q2=df['SALE_AMT'].quantile(0.5)
q3=df['SALE_AMT'].quantile(0.75)
iqr=q3-q1
iqr

3420.0

In [5]:
q3

5100.0

In [6]:
q1

1680.0

In [7]:
df.sort_values('SALE_AMT', ascending=False).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
13953223,2022-03-23,201044,딸기,2.0,880491120.0,1760982240,3,2
5867761,2022-04-02,200131,모듬쌈채류,9999.0,172720.0,1727027280,4,5
5867762,2022-04-02,200131,모듬쌈채류,9999.0,170210.0,1701929790,4,5
5867760,2022-04-02,200131,모듬쌈채류,9000.0,176650.0,1589850000,4,5
2663438,2021-09-26,520000009,망고스틴,1.0,941181000.0,941181000,9,6
2086866,2022-02-10,200000,청량고추,1.0,930144000.0,930144000,2,3
2326423,2022-01-10,22000033,식품,3000.0,300000.0,900000000,1,0
77228,2021-10-18,200047,청상추1봉,1.0,880306000.0,880306000,10,0
985165,2022-08-13,8801051088151,엘자연퐁용기베이킹소다레몬,1.0,880109440.0,880109440,8,5
1074764,2022-07-22,8801056227708,롯데칠성사이다플러스500ml,1.0,880104890.0,880104890,7,4
10730020,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
10730019,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
10730018,2022-01-22,8801045442723,오옥수수유,1.0,880100780.0,880100780,1,5
5617987,2021-08-30,8809102740386,왕란,3.0,288090720.0,864272160,8,0
11065601,2022-04-07,8801118256790,델몬트미니컵홈,1.0,600012450.0,600012450,4,3
12600607,2022-04-05,2734840004703,배선물세트9과,1.0,590020000.0,590020000,4,1
2086865,2021-12-13,200000,청량고추,1.0,518831980.0,518831980,12,0
11274005,2022-09-01,200000,다시마,1.0,490603600.0,490603600,9,3
10990643,2021-08-15,8801115114383,서울우유3651등급우유,2.0,200113900.0,400227800,8,6
12581799,2021-09-18,2734840001641,햇망양파3kg,2.0,200025400.0,400050800,9,5
14031799,2022-08-16,3800111203089,크랄스카레몬보드카,1.0,380011120.0,380011120,8,1
17435823,2021-10-10,351030,국내산돈가브리살,1.0,351028000.0,351028000,10,6
15656019,2022-02-19,2908990004702,쥬키니호박2개,1.0,351010010.0,351010010,2,5
17239005,2022-04-11,351001,국내산돈삼겹살,1.0,351008000.0,351008000,4,0
281922,2022-05-20,211023,식품,1.0,292222000.0,292222000,5,4
11836873,2022-08-20,8809182054694,자연담은쌀21년산햅쌀,5940.0,68000.0,285120000,8,5
12542057,2022-04-20,2000804,천혜향,1.0,279002000.0,279002000,4,2
23272520,2021-09-19,2501130000710,소금20kg,9999.0,27000.0,269973000,9,6
10548340,2022-01-07,255341,생삼겹살구이용,1.0,255103000.0,229592700,1,4
12615352,2022-09-08,290009,과자,1.0,220000570.0,220000570,9,3
13120087,2022-06-06,218100,대패삼겹살수입산,1.0,218231000.0,218231000,6,0
7612764,2021-12-18,201352,섬초,1.0,205356010.0,205356010,12,5
7807807,2021-10-02,22002693,자두,1.0,205260010.0,205260010,10,5
10556480,2021-08-11,2907062812320,건어물,1.0,205203010.0,205203010,8,2
7607424,2022-08-16,201344,흙당근,1.0,205168010.0,205168010,8,1
7595583,2022-05-06,201321,표고버섯국산,1.0,205045000.0,205045000,5,4
7550736,2021-10-24,201176,생강,1.0,205028000.0,205028000,10,6
7589290,2022-09-04,201280,청양고추,1.0,204503000.0,204503000,9,6
7516869,2022-04-01,201004,감자,1.0,204503000.0,204503000,4,4
2475682,2022-06-06,22002662,청과류,1.0,204334000.0,204334000,6,0
7163481,2021-10-04,8801492361608,하림닭볶음탕용900g,1.0,204304000.0,204304000,10,0
4460081,2022-08-22,22007711,델몬트바나나,1.0,204240010.0,204240010,8,0
4301918,2021-09-01,22001665,무우소,1.0,204186020.0,204186020,9,2
4488092,2021-09-25,22010339,노각오이,1.0,204173020.0,204173020,9,5
4094788,2022-09-30,201344,흙당근,1.0,204173000.0,204173000,9,4
4108959,2022-02-12,201443,밤고구마행사,1.0,204126000.0,204126000,2,5
7517380,2022-04-18,201004,감자,1.0,204012000.0,204012000,4,0
4497562,2022-08-29,22010704,청양고추300g,1.0,203259010.0,203259010,8,0
4037071,2021-11-13,201153,봄동,1.0,203170000.0,203170000,11,5
4469928,2022-05-05,22008633,딸기1팩35,1.0,203118010.0,203118010,5,3

In [8]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8801068097474,땅콩샌드,1.0,1100.0,1100,5,3
1,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100,5,5
2,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100,5,5
3,2021-05-30,8801068097474,땅콩샌드,1.0,1100.0,1100,5,6
4,2021-05-31,8801068097474,땅콩샌드,1.0,1100.0,1100,5,0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9556486800210,망고푸딩,1.0,3500.0,3500,8,5
23660708,2022-08-28,9556486800210,망고푸딩,1.0,3500.0,3500,8,6
23660709,2022-09-13,9556486800210,망고푸딩,1.0,3500.0,3500,9,1
23660710,2022-09-20,9556486800210,망고푸딩,1.0,3500.0,3500,9,1
23660711,2022-09-22,9556486800210,망고푸딩,1.0,3500.0,3500,9,3

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23660712 entries, 0 to 23660711
Data columns (total 8 columns):
 #   Column    Dtype
---  ------    -----
 0   SAL_DT    object
 1   PLU_CD    int64
 2   GDS_NM    object
 3   SALE_QTY  float64
 4   SALE_PRC  float64
 5   SALE_AMT  int32
 6   month     int64
 7   weekday   int64
dtypes: float64(2), int32(1), int64(3), object(2)
memory usage: 1.3+ GB

In [10]:
df.isnull().sum()

SAL_DT      0
PLU_CD      0
GDS_NM      0
SALE_QTY    0
SALE_PRC    0
SALE_AMT    0
month       0
weekday     0
dtype: int64

In [11]:
condition=df['SALE_AMT']>q3+1.5*iqr
df[condition]

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
1456,2021-08-27,0,황도복숭아,1.0,25900.0,25900,8,4
1457,2021-08-27,0,황도복숭아,1.0,25900.0,25900,8,4
1461,2022-01-24,13,딸기1팩,2.0,7900.0,15800,1,0
1466,2022-01-24,13,딸기1팩,2.0,7900.0,15800,1,0
1470,2022-01-24,13,딸기1팩,2.0,7900.0,15800,1,0
...,...,...,...,...,...,...,...,...
23660154,2022-07-27,8809772191617,코디순수3겹데코,1.0,17000.0,17000,7,2
23660155,2022-08-26,8809772191617,코디순수3겹데코,1.0,16000.0,16000,8,4
23660156,2022-08-28,8809772191617,코디순수3겹데코,1.0,16000.0,16000,8,6
23660157,2022-09-14,8809772191617,코디순수3겹데코,1.0,17000.0,17000,9,2
23660640,2022-08-13,9002490100070,동서레드블캔,7.0,2300.0,16100,8,5

In [12]:
a=df[condition].index
df.drop(a,inplace=True)

In [13]:
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
0,2021-05-27,8801068097474,땅콩샌드,1.0,1100.0,1100,5,3
1,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100,5,5
2,2021-05-29,8801068097474,땅콩샌드,1.0,1100.0,1100,5,5
3,2021-05-30,8801068097474,땅콩샌드,1.0,1100.0,1100,5,6
4,2021-05-31,8801068097474,땅콩샌드,1.0,1100.0,1100,5,0
...,...,...,...,...,...,...,...,...
23660707,2022-08-27,9556486800210,망고푸딩,1.0,3500.0,3500,8,5
23660708,2022-08-28,9556486800210,망고푸딩,1.0,3500.0,3500,8,6
23660709,2022-09-13,9556486800210,망고푸딩,1.0,3500.0,3500,9,1
23660710,2022-09-20,9556486800210,망고푸딩,1.0,3500.0,3500,9,1
23660711,2022-09-22,9556486800210,망고푸딩,1.0,3500.0,3500,9,3

In [14]:
df.sort_values('SALE_AMT', ascending=False).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
17577687,2021-04-10,461019,냉장부채살,1.0,10230.0,10230,4,5
5945845,2022-01-31,201034,한우양지국거리,1.0,10230.0,10230,1,0
5945777,2022-01-29,201034,한우양지국거리,1.0,10230.0,10230,1,5
17685858,2022-05-13,521001,양념소불고기,1.0,10230.0,10230,5,4
5945769,2022-01-28,201034,한우양지국거리,1.0,10230.0,10230,1,4
5945546,2022-01-20,201034,한우양지국거리,1.0,10230.0,10230,1,3
5954013,2022-04-19,201048,한우다짐육1,1.0,10230.0,10230,4,1
5954018,2022-04-19,201048,한우다짐육1,1.0,10230.0,10230,4,1
5945520,2022-01-20,201034,한우양지국거리,1.0,10230.0,10230,1,3
17540252,2021-09-19,461004,냉장등심국거리,1.0,10230.0,10230,9,6
9325300,2022-02-16,202313,연어회,1.0,10230.0,10230,2,2
13631084,2022-05-13,209104,수입설도호주,1.0,10230.0,10230,5,4
5945510,2022-01-19,201034,한우양지국거리,1.0,10230.0,10230,1,2
5945439,2022-01-17,201034,한우양지국거리,1.0,10230.0,10230,1,0
5945432,2022-01-17,201034,한우양지국거리,1.0,10230.0,10230,1,0
17699338,2021-07-12,521004,양념무뼈닭발,1.0,10230.0,10230,7,0
17350000,2022-02-23,351010,국내산돈뒷다리살,1.0,10230.0,10230,2,2
5945415,2022-01-16,201034,한우양지국거리,1.0,10230.0,10230,1,6
17704473,2021-05-18,521005,양념돈고추장주물럭,1.0,10230.0,10230,5,1
5954034,2022-04-22,201048,한우다짐육1,1.0,10230.0,10230,4,4
5945409,2022-01-16,201034,한우양지국거리,1.0,10230.0,10230,1,6
5945396,2022-01-16,201034,한우양지국거리,1.0,10230.0,10230,1,6
5945358,2022-01-14,201034,한우양지국거리,1.0,10230.0,10230,1,4
17349779,2022-02-14,351010,국내산돈뒷다리살,1.0,10230.0,10230,2,0
5945343,2022-01-14,201034,한우양지국거리,1.0,10230.0,10230,1,4
5945334,2022-01-14,201034,한우양지국거리,1.0,10230.0,10230,1,4
10516667,2022-06-16,2052030,수입우삼겹양지500g,1.0,10230.0,10230,6,3
7687600,2021-09-18,204324,한돈등뼈,1.0,10230.0,10230,9,5
5945317,2022-01-13,201034,한우양지국거리,1.0,10230.0,10230,1,3
5945783,2022-01-29,201034,한우양지국거리,1.0,10230.0,10230,1,5
4147495,2022-04-01,203033,한우국거리,1.0,10230.0,10230,4,4
5945251,2022-01-11,201034,한우양지국거리,1.0,10230.0,10230,1,1
4146056,2021-12-17,203033,한우국거리,1.0,10230.0,10230,12,4
6015518,2022-01-31,201257,한돈앞다리제육불고기,1.0,10230.0,10230,1,0
5946650,2022-03-10,201034,한우양지국거리,1.0,10230.0,10230,3,3
11952964,2022-07-16,206017,한우국거리,1.0,10230.0,10230,7,5
11952965,2022-07-16,206017,한우국거리,1.0,10230.0,10230,7,5
6015669,2022-02-13,201257,한돈앞다리제육불고기,1.0,10230.0,10230,2,6
17550834,2022-03-05,461012,냉장치마살,1.0,10230.0,10230,3,5
5946569,2022-03-07,201034,한우양지국거리,1.0,10230.0,10230,3,0
17550835,2022-03-05,461012,냉장치마살,1.0,10230.0,10230,3,5
4146023,2021-12-14,203033,한우국거리,1.0,10230.0,10230,12,1
5946451,2022-03-01,201034,한우양지국거리,1.0,10230.0,10230,3,1
7655640,2022-05-29,204055,브랜드생삼겹살,1.0,10230.0,10230,5,6
5946432,2022-02-28,201034,한우양지국거리,1.0,10230.0,10230,2,0
5946428,2022-02-28,201034,한우양지국거리,1.0,10230.0,10230,2,0
5946427,2022-02-28,201034,한우양지국거리,1.0,10230.0,10230,2,0
5953937,2022-04-05,201048,한우다짐육1,1.0,10230.0,10230,4,1
17702302,2020-12-25,521005,양념돈고추장주물럭,1.0,10230.0,10230,12,4
5946160,2022-02-14,201034,한우양지국거리,1.0,10230.0,10230,2,0

In [15]:
df.sort_values('SALE_QTY', ascending=False).head(50)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday
23304225,2021-11-06,2599990000117,잡화,9999.0,400000.0,-2147483648,11,5
14026309,2021-11-25,290000001480,조이사시장,656.0,10.0,6560,11,3
14025758,2021-11-22,290000001480,조이사시장,333.0,10.0,3330,11,0
14027292,2021-12-05,290000001480,조이사시장,333.0,10.0,3330,12,6
14027293,2021-12-05,290000001480,조이사시장,333.0,10.0,3330,12,6
14027291,2021-12-05,290000001480,조이사시장,333.0,10.0,3330,12,6
23306786,2022-05-29,2599990000247,공병100원,102.0,100.0,10200,5,6
23306970,2022-08-12,2599990000247,공병100원,102.0,100.0,10200,8,4
23306825,2022-06-12,2599990000247,공병100원,101.0,100.0,10100,6,6
23306619,2022-04-04,2599990000247,공병100원,101.0,100.0,10100,4,0
23306061,2021-10-21,2599990000247,공병100원,100.0,100.0,10000,10,3
23306312,2022-01-05,2599990000247,공병100원,100.0,100.0,10000,1,2
23306098,2021-10-31,2599990000247,공병100원,100.0,100.0,10000,10,6
23306427,2022-02-06,2599990000247,공병100원,100.0,100.0,10000,2,6
23306002,2021-10-02,2599990000247,공병100원,100.0,100.0,10000,10,5
23307084,2022-09-23,2599990000247,공병100원,100.0,100.0,10000,9,4
10558008,2021-08-11,3309999000044,식품,100.0,100.0,10000,8,2
23306746,2022-05-16,2599990000247,공병100원,100.0,100.0,10000,5,0
23306184,2021-11-27,2599990000247,공병100원,100.0,100.0,10000,11,5
23306911,2022-07-17,2599990000247,공병100원,100.0,100.0,10000,7,6
23306657,2022-04-16,2599990000247,공병100원,100.0,100.0,10000,4,5
23306895,2022-07-08,2599990000247,공병100원,100.0,100.0,10000,7,4
11513254,2022-07-29,2900000000223,배달용봉투,100.0,50.0,5000,7,4
10557282,2022-09-26,33002,납부필증칩3L,100.0,100.0,10000,9,0
23306440,2022-02-10,2599990000247,공병100원,100.0,100.0,10000,2,3
23306998,2022-08-25,2599990000247,공병100원,100.0,100.0,10000,8,3
23306504,2022-03-03,2599990000247,공병100원,99.0,100.0,9900,3,3
23306785,2022-05-29,2599990000247,공병100원,99.0,100.0,9900,5,6
23307071,2022-09-19,2599990000247,공병100원,98.0,100.0,9800,9,0
23306792,2022-06-01,2599990000247,공병100원,97.0,100.0,9700,6,2
23306795,2022-06-01,2599990000247,공병100원,97.0,100.0,9700,6,2
23306794,2022-06-01,2599990000247,공병100원,97.0,100.0,9700,6,2
23306793,2022-06-01,2599990000247,공병100원,97.0,100.0,9700,6,2
23306166,2021-11-20,2599990000247,공병100원,96.0,100.0,9600,11,5
23306328,2022-01-08,2599990000247,공병100원,95.0,100.0,9500,1,5
23306354,2022-01-18,2599990000247,공병100원,95.0,100.0,9500,1,1
23306835,2022-06-15,2599990000247,공병100원,93.0,100.0,9300,6,2
23306543,2022-03-13,2599990000247,공병100원,93.0,100.0,9300,3,6
23306932,2022-07-29,2599990000247,공병100원,92.0,100.0,9200,7,4
23306950,2022-08-03,2599990000247,공병100원,87.0,100.0,8700,8,2
23306749,2022-05-16,2599990000247,공병100원,87.0,100.0,8700,5,0
23306635,2022-04-08,2599990000247,공병100원,86.0,100.0,8600,4,4
23306959,2022-08-07,2599990000247,공병100원,83.0,100.0,8300,8,6
23306712,2022-05-05,2599990000247,공병100원,83.0,100.0,8300,5,3
23306782,2022-05-29,2599990000247,공병100원,82.0,100.0,8200,5,6
23306496,2022-02-28,2599990000247,공병100원,82.0,100.0,8200,2,0
23306393,2022-01-30,2599990000247,공병100원,81.0,100.0,8100,1,6
23306997,2022-08-25,2599990000247,공병100원,80.0,100.0,8000,8,3
23307003,2022-08-27,2599990000247,공병100원,80.0,100.0,8000,8,5
23305997,2021-10-02,2599990000247,공병100원,80.0,100.0,8000,10,5