In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

base_path = ''

In [2]:
df = pd.read_csv(base_path + 'data1019.csv')
df

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
0,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
1,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
2,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
3,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
4,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
...,...,...,...,...,...,...,...,...,...,...
13085615,2022-09-29,8809267390136,서라벌특란30구,1,7800,7800,9,3,두부/콩나물/계란,일반계란
13085616,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085617,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085618,2022-09-30,8809267390136,서라벌특란30구,2,7800,15600,9,4,두부/콩나물/계란,일반계란
13085619,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란

In [3]:
df.sort_values('SALE_QTY', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
615753,2022-01-14,200160,백오이,9999,2480,24797520,1,4,채소,오이
9427107,2022-04-21,8809517210078,에그탑특란,9999,10000,79792020,4,3,두부/콩나물/계란,계란
4882840,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999,3900,38996100,5,1,소스/양념/조미료,조미료
13068571,2021-09-19,2501130000710,소금20kg,9999,27000,269973000,9,6,소스/양념/조미료,조미료
...,...,...,...,...,...,...,...,...,...,...
3526791,2021-11-27,204219,한돈앞다리살수육용,0,14500,0,11,5,돼지고기,돼지고기앞다리살
6353115,2022-03-27,8801115114338,서울목장저지방우유,0,3600,0,3,6,유제품,일반우유
7666252,2022-07-12,8801007769783,백설고소함가득참기름,0,8950,0,7,1,소스/양념/조미료,조미료
3526806,2021-11-29,204219,한돈앞다리살수육용,0,12000,0,11,0,돼지고기,돼지고기앞다리살
4465171,2021-10-03,8801024946457,종가집숨쉬는전통콩나물,0,1450,0,10,6,두부/콩나물/계란,콩나물

In [4]:
df.sort_values('SALE_PRC', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1503183,2022-03-23,201044,딸기,2,880491120,1760982240,3,2,과일,딸기
530840,2021-10-18,200047,청상추1봉,1,880306000,880306000,10,0,채소,상추
12181523,2021-10-10,351030,국내산돈가브리살,1,351028000,351028000,10,6,정육,등심덧살
11986628,2022-04-11,351001,국내산돈삼겹살,1,351008000,351008000,4,0,정육,돼지고기
1683594,2022-04-20,2000804,천혜향,1,279002000,279002000,4,2,과일,만감류
...,...,...,...,...,...,...,...,...,...,...
1812729,2022-02-16,3074,누드애호박개,1,0,0,2,2,채소,호박
1512675,2022-05-07,201463,딸기,1,0,0,5,5,과일,딸기
676880,2022-03-13,200223,애호박,1,0,0,3,6,채소,애호박
1812730,2022-02-26,3074,누드애호박개,1,0,0,2,5,채소,호박
646445,2022-02-24,22001146,백오이,1,0,0,2,3,채소,오이

In [5]:
df.sort_values('SALE_AMT', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1503183,2022-03-23,201044,딸기,2,880491120,1760982240,3,2,과일,딸기
530840,2021-10-18,200047,청상추1봉,1,880306000,880306000,10,0,채소,상추
12181523,2021-10-10,351030,국내산돈가브리살,1,351028000,351028000,10,6,정육,등심덧살
11986628,2022-04-11,351001,국내산돈삼겹살,1,351008000,351008000,4,0,정육,돼지고기
9954989,2022-08-20,8809182054694,자연담은쌀21년산햅쌀,5940,68000,285120000,8,5,양곡,쌀
...,...,...,...,...,...,...,...,...,...,...
7072916,2021-09-01,8850389106211,모구모구복숭아,0,1500,0,9,2,생수/음료/커피,과일주스
7072913,2021-08-31,8850389106211,모구모구복숭아,0,1500,0,8,1,생수/음료/커피,과일주스
7072912,2021-08-31,8850389106211,모구모구복숭아,0,1500,0,8,1,생수/음료/커피,과일주스
7047933,2022-06-15,8809331505657,아워홈요리두부찌개,0,1500,0,6,2,두부/콩나물/계란,두부
4346730,2021-11-21,8801007851891,CJ더건강한직화구이햄,0,2800,0,11,6,냉장식품,냉장간편식품

In [6]:
df.sort_values('SALE_PRC', ascending=False).head(10)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1503183,2022-03-23,201044,딸기,2,880491120,1760982240,3,2,과일,딸기
530840,2021-10-18,200047,청상추1봉,1,880306000,880306000,10,0,채소,상추
12181523,2021-10-10,351030,국내산돈가브리살,1,351028000,351028000,10,6,정육,등심덧살
11986628,2022-04-11,351001,국내산돈삼겹살,1,351008000,351008000,4,0,정육,돼지고기
1683594,2022-04-20,2000804,천혜향,1,279002000,279002000,4,2,과일,만감류
9693429,2022-01-07,255341,생삼겹살구이용,1,255103000,229592700,1,4,정육,삼겹살
1644590,2021-12-18,201352,섬초,1,205356010,205356010,12,5,채소,섬초
2165377,2021-10-02,22002693,자두,1,205260010,205260010,10,5,과일,자두
1022419,2022-08-16,201344,흙당근,1,205168010,205168010,8,1,채소,당근
8993799,2022-05-06,201321,표고버섯국산,1,205045000,205045000,5,4,채소,표고버섯

df1 = df[df['SALE_PRC'] < 150000]
df1

df1.sort_values('SALE_PRC', ascending=False).head(50)

In [7]:
df.sort_values('SALE_AMT', ascending=False).head(10)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1503183,2022-03-23,201044,딸기,2,880491120,1760982240,3,2,과일,딸기
530840,2021-10-18,200047,청상추1봉,1,880306000,880306000,10,0,채소,상추
12181523,2021-10-10,351030,국내산돈가브리살,1,351028000,351028000,10,6,정육,등심덧살
11986628,2022-04-11,351001,국내산돈삼겹살,1,351008000,351008000,4,0,정육,돼지고기
9954989,2022-08-20,8809182054694,자연담은쌀21년산햅쌀,5940,68000,285120000,8,5,양곡,쌀
1683594,2022-04-20,2000804,천혜향,1,279002000,279002000,4,2,과일,만감류
13068571,2021-09-19,2501130000710,소금20kg,9999,27000,269973000,9,6,소스/양념/조미료,조미료
9693429,2022-01-07,255341,생삼겹살구이용,1,255103000,229592700,1,4,정육,삼겹살
1644590,2021-12-18,201352,섬초,1,205356010,205356010,12,5,채소,섬초
2165377,2021-10-02,22002693,자두,1,205260010,205260010,10,5,과일,자두

In [15]:
df1 = df[df['SALE_AMT'] < 200002900]

In [16]:
df1.sort_values('SALE_AMT', ascending=False).head(30)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
7710975,2021-10-31,8801033786259,베지밀B,7256,14800,107388800,10,6,유제품,두유
8671856,2022-04-02,6971804652211,딸기모양젤리,1789,90000,100184000,4,5,과자/대용식,젤리
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
7678308,2022-07-04,8801013120479,큐원갈색설탕,9000,12500,99000000,7,0,소스/양념/조미료,조미료
7363914,2022-03-03,22002853,스치딸기1kg행사,7020,14800,89856000,3,3,과일,딸기
8677163,2022-07-04,8801007144641,CJ갈색설탕,9000,14500,89100000,7,0,소스/양념/조미료,조미료
1689210,2022-09-12,2200408605779,샤인머스켓,999,86500,86413500,9,0,과일,포도
7677194,2022-07-04,8801013113136,큐원하얀설탕,9000,11500,85320000,7,0,소스/양념/조미료,조미료
9427107,2022-04-21,8809517210078,에그탑특란,9999,10000,79792020,4,3,두부/콩나물/계란,계란
2628402,2022-09-13,8801119740151,테라캔500ml6입,5600,14000,78400000,9,1,주류,맥주
8677211,2022-07-04,8801007227320,CJ백설하얀설탕,9000,12000,71820000,7,0,소스/양념/조미료,조미료
1450751,2022-03-25,2002033,한라봉,7900,7900,62410000,3,4,과일,만감류
13081014,2021-11-26,8801115111030,서울우유18ℓ,9000,5800,52200000,11,4,유제품,일반우유
10090217,2022-03-06,8802272111260,일판특란30구,6900,6980,48162000,3,6,두부/콩나물/계란,계란
9547012,2021-07-12,8801115111030,서울우유18,8888,5000,44440000,7,0,유제품,일반우유
10101891,2021-10-22,8809267390792,신선특란30구,5980,6980,41740400,10,4,두부/콩나물/계란,계란
10088453,2021-12-12,8802272111260,일판특란30구,4980,7900,39342000,12,6,두부/콩나물/계란,계란
4882840,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999,3900,38996100,5,1,소스/양념/조미료,조미료
10089276,2022-01-13,8802272111260,일판특란30구,5980,6480,38750400,1,3,두부/콩나물/계란,계란
7516480,2021-11-13,2222000025007,샤인머스켓2kg,1795,19800,35541000,11,5,과일,포도
11950210,2022-07-16,2999000034581,꿀수박59kg이상1통행사,2000,15800,31600000,7,5,과일,수박
12000645,2021-06-06,351003,국내산대패삼겹살,2355,11590,27294450,6,6,정육,돼지고기
2474439,2022-03-02,8801094012502,코카콜라2L,7889,3400,26822600,3,2,생수/음료/커피,콜라
2474440,2022-03-02,8801094012502,코카콜라2L,7889,3400,26822600,3,2,생수/음료/커피,콜라
10135035,2021-11-06,2456785966082,종이컵1박스1000개,2960,9000,26640000,11,5,주방용품,일회용컵
9937256,2021-10-20,8801117149109,오예감실속형기획,6662,4980,26514760,10,2,과자/대용식,과자
3504416,2022-04-12,204034,한우1등급전각국거리,2600,10000,26000000,4,1,정육,소고기
7882242,2021-10-06,8801052036212,청정원양조진간장깊은맛,5802,4400,25528800,10,2,소스/양념/조미료,조미료
10278211,2022-04-11,8806006508227,유한락스후로랄1L12,8076,3100,25035600,4,0,세탁용품,세탁용품
615753,2022-01-14,200160,백오이,9999,2480,24797520,1,4,채소,오이

In [12]:
df1

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
0,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
1,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
2,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
3,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
4,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
...,...,...,...,...,...,...,...,...,...,...
13085615,2022-09-29,8809267390136,서라벌특란30구,1,7800,7800,9,3,두부/콩나물/계란,일반계란
13085616,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085617,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085618,2022-09-30,8809267390136,서라벌특란30구,2,7800,15600,9,4,두부/콩나물/계란,일반계란
13085619,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란

In [17]:
df1.sort_values('SALE_QTY', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
9427107,2022-04-21,8809517210078,에그탑특란,9999,10000,79792020,4,3,두부/콩나물/계란,계란
615753,2022-01-14,200160,백오이,9999,2480,24797520,1,4,채소,오이
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
4882840,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999,3900,38996100,5,1,소스/양념/조미료,조미료
5142604,2021-04-03,8801048101023,진로이즈백,9982,1350,13475700,4,5,주류,소주
...,...,...,...,...,...,...,...,...,...,...
6764406,2022-07-18,8801299300046,삼부자광천돌자반,0,3950,0,7,0,건조식품,김
1316720,2021-12-17,22001191,달래,0,1500,0,12,4,채소,달래
1316721,2021-12-17,22001191,달래,0,1500,0,12,4,채소,달래
1316722,2021-12-18,22001191,달래,0,1500,0,12,5,채소,달래
3783538,2022-06-11,201500,미니파프리카,0,2500,0,6,5,채소,파프리카

In [18]:
df1.sort_values('SALE_PRC', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
1594146,2022-09-22,202103,무화과,1,18000000,18000000,9,3,과일,무화과
2885549,2022-07-22,200049,햇감자,1,7027370,7027370,7,4,채소,감자
2885548,2022-07-22,200049,햇감자,1,7027370,7027370,7,4,채소,감자
9647108,2022-02-03,1237,음료묶음,1,1800000,1800000,2,3,생수/음료/커피,음료
9647110,2022-02-03,1237,음료묶음,1,1800000,1800000,2,3,생수/음료/커피,음료
...,...,...,...,...,...,...,...,...,...,...
1733630,2022-08-10,3029,묶음깻잎1봉,1,0,0,8,2,야채,깻잎
1733629,2022-07-25,3029,묶음깻잎1봉,1,0,0,7,0,야채,깻잎
1733628,2022-07-22,3029,묶음깻잎1봉,1,0,0,7,4,야채,깻잎
2097088,2021-12-17,333,백오이2개1팩,1,0,0,12,4,채소,오이
1733625,2022-07-17,3029,묶음깻잎1봉,3,0,0,7,6,야채,깻잎

In [19]:
df1.sort_values('SALE_AMT', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
7710975,2021-10-31,8801033786259,베지밀B,7256,14800,107388800,10,6,유제품,두유
8671856,2022-04-02,6971804652211,딸기모양젤리,1789,90000,100184000,4,5,과자/대용식,젤리
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
7678308,2022-07-04,8801013120479,큐원갈색설탕,9000,12500,99000000,7,0,소스/양념/조미료,조미료
7363914,2022-03-03,22002853,스치딸기1kg행사,7020,14800,89856000,3,3,과일,딸기
...,...,...,...,...,...,...,...,...,...,...
8489315,2022-02-19,201034,한우양지국거리,0,5500,0,2,5,정육,소고기
8489429,2022-02-26,201034,한우양지국거리,0,5500,0,2,5,정육,소고기
8489432,2022-02-26,201034,한우양지국거리,0,5500,0,2,5,정육,소고기
8489518,2022-03-02,201034,한우양지국거리,0,11000,0,3,2,정육,소고기
7605999,2021-08-20,8801104301862,빙그레요구르트,0,1050,0,8,4,유제품,요구르트

In [39]:
df2 = df1[df1['SALE_PRC'] < 151800]

In [40]:
df2.sort_values('SALE_PRC', ascending=False).head(30)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
7223718,2022-04-15,209101,한돈생삼겹살,1,151530,151530,4,4,정육,삼겹살
9459759,2021-09-19,521009,양념소LA갈비,1,151350,151350,9,6,정육,소고기갈비
1635846,2021-10-15,202110,생율,1,150200,150200,10,4,채소,생율
9453122,2021-04-12,711015,한우꽃등심,1,150120,150120,4,0,정육,등심
1590223,2022-04-15,202204,추희자두,1,150100,150100,4,4,과일,자두
3477067,2021-11-15,202111,찰토마토,1,150100,150100,11,0,과일,토마토
3519722,2022-09-08,206031,LA갈비,1,150000,150000,9,3,정육,소고기갈비
3529592,2022-09-03,204219,한돈앞다리살수육용,1,150000,150000,9,5,돼지고기,돼지고기앞다리살
8495449,2022-04-29,218428,한우양지국거리,1,150000,150000,4,4,정육,소고기
8543626,2021-12-14,201243,한돈흑돼지생오겹살구이,1,150000,150000,12,1,정육,삼겹살
9452706,2021-01-17,711015,한우꽃등심,1,150000,150000,1,6,정육,등심
9646977,2021-09-28,1237,음료묶음,1,150000,150000,9,1,생수/음료/커피,음료
9452807,2021-02-11,711015,한우꽃등심,1,150000,150000,2,3,정육,등심
9452851,2021-02-19,711015,한우꽃등심,1,150000,150000,2,4,정육,등심
8574629,2021-10-21,201290,한돈생오겹살수육보쌈,1,150000,150000,10,3,정육,삼겹살
3519715,2022-09-04,206031,LA갈비,1,150000,150000,9,6,정육,소고기갈비
3529593,2022-09-03,204219,한돈앞다리살수육용,1,150000,150000,9,5,돼지고기,돼지고기앞다리살
9453504,2021-06-24,711015,한우꽃등심,8,150000,1200000,6,3,정육,등심
3519634,2022-08-05,203112,LA갈비,1,150000,150000,8,4,정육,소고기갈비
3519581,2022-02-01,203112,LA갈비,1,150000,150000,2,1,정육,소고기갈비
3529591,2022-09-03,204219,한돈앞다리살수육용,1,150000,150000,9,5,돼지고기,돼지고기앞다리살
3519578,2022-01-30,203112,LA갈비,1,150000,150000,1,6,정육,소고기갈비
8490897,2022-05-13,201034,한우양지국거리,1,150000,150000,5,4,정육,소고기
7250443,2022-09-07,204302,한돈돼지갈비,1,150000,150000,9,2,정육,갈비
7238862,2022-07-27,203151,돈생삼겹살,1,150000,150000,7,2,정육,돼지고기
7238911,2022-07-31,203151,돈생삼겹살,1,150000,150000,7,6,정육,돼지고기
215841,2021-09-17,201170,상추,1,150000,150000,9,4,채소,상추
3529594,2022-09-03,204219,한돈앞다리살수육용,1,150000,150000,9,5,돼지고기,돼지고기앞다리살
1500633,2022-02-13,2000801,딸기,1,150000,150000,2,6,과일,딸기
9453835,2021-09-15,711015,한우꽃등심,8,150000,1200000,9,2,정육,등심

In [41]:
df2

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
0,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
1,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
2,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
3,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
4,2021-07-24,0,황도복숭아,1,5980,5980,7,5,과일,복숭아
...,...,...,...,...,...,...,...,...,...,...
13085615,2022-09-29,8809267390136,서라벌특란30구,1,7800,7800,9,3,두부/콩나물/계란,일반계란
13085616,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085617,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란
13085618,2022-09-30,8809267390136,서라벌특란30구,2,7800,15600,9,4,두부/콩나물/계란,일반계란
13085619,2022-09-30,8809267390136,서라벌특란30구,1,7800,7800,9,4,두부/콩나물/계란,일반계란

In [42]:
df2.sort_values('SALE_QTY', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
9427107,2022-04-21,8809517210078,에그탑특란,9999,10000,79792020,4,3,두부/콩나물/계란,계란
4882840,2022-05-24,8801045420042,오뚜기바삭하고고소한튀김가루,9999,3900,38996100,5,1,소스/양념/조미료,조미료
615753,2022-01-14,200160,백오이,9999,2480,24797520,1,4,채소,오이
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
5142604,2021-04-03,8801048101023,진로이즈백,9982,1350,13475700,4,5,주류,소주
...,...,...,...,...,...,...,...,...,...,...
8580056,2022-05-19,201370,프라임척아이롤구이,0,3300,0,5,3,정육,소고기
380616,2022-06-16,23000636,느타리버섯,0,700,0,6,3,채소,버섯
8649214,2021-12-17,2200408601948,산청설향딸기특34,0,7980,0,12,4,과일,딸기
2429114,2022-07-31,8801068107562,삼립미니꿀약과,0,1800,0,7,6,과자/대용식,밀가루스낵
6099980,2021-09-26,8801111922517,크라운콘칩,0,3000,0,9,6,과자/대용식,과자

In [43]:
df2.sort_values('SALE_PRC', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
7223718,2022-04-15,209101,한돈생삼겹살,1,151530,151530,4,4,정육,삼겹살
9459759,2021-09-19,521009,양념소LA갈비,1,151350,151350,9,6,정육,소고기갈비
1635846,2021-10-15,202110,생율,1,150200,150200,10,4,채소,생율
9453122,2021-04-12,711015,한우꽃등심,1,150120,150120,4,0,정육,등심
1590223,2022-04-15,202204,추희자두,1,150100,150100,4,4,과일,자두
...,...,...,...,...,...,...,...,...,...,...
2157667,2022-07-13,4015,말랑이복숭아910수1박스,1,0,0,7,2,과일,복숭아
1812718,2022-01-15,3074,누드애호박개,1,0,0,1,5,채소,호박
1812719,2022-01-17,3074,누드애호박개,1,0,0,1,0,채소,호박
1812720,2022-01-18,3074,누드애호박개,1,0,0,1,1,채소,호박
1812717,2022-01-12,3074,누드애호박개,1,0,0,1,2,채소,호박

In [44]:
df2.sort_values('SALE_AMT', ascending=False)

,SAL_DT,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,month,weekday,대분류,소분류
7710975,2021-10-31,8801033786259,베지밀B,7256,14800,107388800,10,6,유제품,두유
8671856,2022-04-02,6971804652211,딸기모양젤리,1789,90000,100184000,4,5,과자/대용식,젤리
1486199,2022-03-17,202024,딸기,9999,10000,99990000,3,3,과일,딸기
7678308,2022-07-04,8801013120479,큐원갈색설탕,9000,12500,99000000,7,0,소스/양념/조미료,조미료
7363914,2022-03-03,22002853,스치딸기1kg행사,7020,14800,89856000,3,3,과일,딸기
...,...,...,...,...,...,...,...,...,...,...
3592969,2021-10-11,204260,한돈생등뼈,0,10000,0,10,0,정육,부산물
8486889,2021-11-07,201034,한우양지국거리,0,5500,0,11,6,정육,소고기
8486892,2021-11-07,201034,한우양지국거리,0,5500,0,11,6,정육,소고기
3592971,2021-10-11,204260,한돈생등뼈,0,10000,0,10,0,정육,부산물
7255191,2022-02-22,203170,한돈돼지등뼈,0,2500,0,2,1,정육,등뼈

In [45]:
df2.to_csv('df1019_1.csv', index=False)