In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''

In [2]:
# a 마트 gds+list+dtl
amartsum = pd.read_csv(base_path + 'amartsum.csv')
amartsum

C:\Users\min\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID
0,20210901,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,71138,9000000.0,NaN
1,20210901,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,71138,9000000.0,NaN
2,20210901,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,71138,9000000.0,NaN
3,20210901,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,71138,9000000.0,NaN
4,20210901,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,71138,9000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968529,20220901,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,125736,5000.0,012018_1636
4968530,20220901,12018,7,242,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,142401,5000.0,NaN
4968531,20220901,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,142602,10000.0,012018_6700
4968532,20220901,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,162924,5000.0,012018_2764
4968533,20220901,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,162937,22600.0,012018_4787

In [13]:
amartsum['SALE_KIND_TP_NM'].value_counts()

매출      4907080
배달매출      32147
배달착불      29307
Name: SALE_KIND_TP_NM, dtype: int64

In [12]:
amartsum.isnull().sum()

SAL_DT                  0
STR_CD                  0
POS_NO                  0
TRAN_NO                 0
SEQ_NO                  0
DESI_CNCL_TP_NM         0
SALE_RTN_SGN            0
PLU_CD                  0
GDS_CLSS_CD             0
SALE_QTY                0
SALE_PRC                0
SALE_AMT                0
GDS_NM                  0
SALE_KIND_TP_NM         0
REAL_SAL_DT             0
REAL_SAL_TTM            0
PAY_AMT                 0
MSHP_ID            688555
dtype: int64

In [3]:
a = amartsum.loc[amartsum['SALE_KIND_TP_NM'].isin(['매출'])]
a

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID
0,20210901,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,71138,9000000.0,NaN
1,20210901,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,71138,9000000.0,NaN
2,20210901,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,71138,9000000.0,NaN
3,20210901,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,71138,9000000.0,NaN
4,20210901,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,71138,9000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968529,20220901,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,125736,5000.0,012018_1636
4968530,20220901,12018,7,242,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,142401,5000.0,NaN
4968531,20220901,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,142602,10000.0,012018_6700
4968532,20220901,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,162924,5000.0,012018_2764
4968533,20220901,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,162937,22600.0,012018_4787

In [26]:
pd.set_option('display.max_row', 300)

In [28]:
a['MSHP_ID'].sort_values(ascending=False).head(300)

4051082    012018_9999
1244168    012018_9999
4051079    012018_9999
4051080    012018_9999
4051081    012018_9999
4673174    012018_9999
4673175    012018_9999
4673176    012018_9999
2204131    012018_9999
1244166    012018_9999
1244167    012018_9999
1244169    012018_9999
2755910    012018_9999
1244170    012018_9999
1244171    012018_9999
2755916    012018_9999
1244172    012018_9999
1244173    012018_9999
4261855    012018_9999
1244174    012018_9999
2755908    012018_9999
2755909    012018_9999
2755917    012018_9999
2755918    012018_9999
2204127    012018_9999
4261856    012018_9999
4779632    012018_9999
4779631    012018_9999
4874899    012018_9999
2204128    012018_9999
4667828    012018_9999
4874900    012018_9999
2204130    012018_9999
4234381    012018_9999
4234380    012018_9999
2201081    012018_9999
2201082    012018_9999
2201083    012018_9999
2201084    012018_9999
1733420    012018_9999
2201085    012018_9999
4261859    012018_9999
2201086    012018_9999
4261858    012018_9999
4261857    012018_9999
4261854    012018_9999
2204129    012018_9999
3190205    012018_9999
3190194    012018_9999
2744431    012018_9999
2744430    012018_9999
2204135    012018_9999
2744429    012018_9999
2744428    012018_9999
3190192    012018_9999
2201087    012018_9999
2204136    012018_9999
2204133    012018_9999
2201088    012018_9999
2201089    012018_9999
4608517    012018_9999
4608518    012018_9999
4049237    012018_9999
4571216    012018_9999
4571215    012018_9999
3190204    012018_9999
2755915    012018_9999
2204134    012018_9999
3190193    012018_9999
2744427    012018_9999
2755913    012018_9999
3190198    012018_9999
2755912    012018_9999
3190202    012018_9999
3190201    012018_9999
2755914    012018_9999
4049238    012018_9999
2744432    012018_9999
2204132    012018_9999
3190200    012018_9999
3190199    012018_9999
3190203    012018_9999
3190197    012018_9999
3190196    012018_9999
3190195    012018_9999
2755911    012018_9999
694498     012018_9998
1373024    012018_9998
694497     012018_9998
1354781    012018_9998
1354780    012018_9998
712705     012018_9998
1373025    012018_9998
2404057    012018_9998
1373026    012018_9998
2404056    012018_9998
1354782    012018_9998
1265333    012018_9998
694499     012018_9998
694500     012018_9998
694501     012018_9998
694502     012018_9998
1265332    012018_9998
694503     012018_9998
712706     012018_9998
712703     012018_9998
2401108    012018_9998
2401107    012018_9998
1265334    012018_9998
2401106    012018_9998
712707     012018_9998
712704     012018_9998
1372275    012018_9998
2728880    012018_9998
1373023    012018_9998
3486513    012018_9998
1389856    012018_9998
1389857    012018_9998
1389858    012018_9998
1372281    012018_9998
2401109    012018_9998
1372280    012018_9998
1372279    012018_9998
1372278    012018_9998
1372277    012018_9998
1372276    012018_9998
1389859    012018_9998
1372274    012018_9998
1389860    012018_9998
1389861    012018_9998
1389862    012018_9998
3274843    012018_9998
3486512    012018_9998
3486511    012018_9998
3486510    012018_9998
3486509    012018_9998
3486508    012018_9998
1373022    012018_9998
2404055    012018_9998
2728881    012018_9998
1164731    012018_9998
1357205    012018_9998
1265331    012018_9998
1357209    012018_9998
2404061    012018_9998
1164735    012018_9998
674743     012018_9998
3274842    012018_9998
674742     012018_9998
674741     012018_9998
1164730    012018_9998
674740     012018_9998
674739     012018_9998
674738     012018_9998
1164729    012018_9998
1164732    012018_9998
3274841    012018_9998
980505     012018_9998
3885838    012018_9998
3885837    012018_9998
3274840    012018_9998
1164736    012018_9998
3274839    012018_9998
3274838    012018_9998
1164737    012018_9998
2386334    012018_9998
1164738    012018_9998
2404060    012018_9998
2404062    012018_9998
1357208    012018_9998
980501     012018_9998
980504     012018_9998
980503     012018_9998
2714701    012018_9998
2714700    012018_9998
2714699    012018_9998
2714698    012018_9998
1265330    012018_9998
2714697    012018_9998
2714696    012018_9998
980502     012018_9998
2386333    012018_9998
2404058    012018_9998
2404059    012018_9998
1357207    012018_9998
1357206    012018_9998
1164733    012018_9998
1357204    012018_9998
1164734    012018_9998
980500     012018_9998
2397868    012018_9997
2397872    012018_9997
2397869    012018_9997
2397870    012018_9997
2397877    012018_9997
2397866    012018_9997
690503     012018_9997
2397871    012018_9997
4917430    012018_9997
2397873    012018_9997
2397874    012018_9997
2397875    012018_9997
2397876    012018_9997
2397867    012018_9997
779456     012018_9997
2397878    012018_9997
2397879    012018_9997
2397880    012018_9997
2397881    012018_9997
779464     012018_9997
2397864    012018_9997
4459210    012018_9997
4459209    012018_9997
779463     012018_9997
779462     012018_9997
779461     012018_9997
690502     012018_9997
779460     012018_9997
779459     012018_9997
779458     012018_9997
779457     012018_9997
779455     012018_9997
779454     012018_9997
779453     012018_9997
779452     012018_9997
779451     012018_9997
4527135    012018_9997
3052621    012018_9997
3052622    012018_9997
3052623    012018_9997
3052624    012018_9997
3052625    012018_9997
2397865    012018_9997
3712620    012018_9997
2397863    012018_9997
3046321    012018_9997
2627932    012018_9997
2627933    012018_9997
425841     012018_9997
425840     012018_9997
425839     012018_9997
3046324    012018_9997
3046323    012018_9997
3046322    012018_9997
3046320    012018_9997
2627930    012018_9997
425838     012018_9997
2947693    012018_9997
2947694    012018_9997
2947695    012018_9997
2947696    012018_9997
2397862    012018_9997
425836     012018_9997
425835     012018_9997
2627931    012018_9997
2627929    012018_9997
425833     012018_9997
425843     012018_9997
425849     012018_9997
425848     012018_9997
425847     012018_9997
425846     012018_9997
425845     012018_9997
425844     012018_9997
2627918    012018_9997
2627919    012018_9997
425842     012018_9997
2627928    012018_9997
2627920    012018_9997
2627921    012018_9997
2627922    012018_9997
2627923    012018_9997
2627924    012018_9997
2627925    012018_9997
2627926    012018_9997
2627927    012018_9997
425834     012018_9997
425837     012018_9997
2973716    012018_9997
425832     012018_9997
2973719    012018_9997
2973718    012018_9997
2973717    012018_9997
3712621    012018_9997
2895045    012018_9997
2895046    012018_9997
2895047    012018_9997
2973721    012018_9997
690507     012018_9997
690506     012018_9997
4874563    012018_9997
2895048    012018_9997
2973720    012018_9997
2397861    012018_9997
690504     012018_9997
690505     012018_9997
4699017    012018_9996
4059232    012018_9996
4699015    012018_9996
4699016    012018_9996
Name: MSHP_ID, dtype: object

In [4]:
b = a.dropna(subset=['MSHP_ID'])
b

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID
32,20210902,12018,01,457,1,정상판매,1,8801039939499,12301.0,1.0,2980.0,2980.0,해표 더고소한 파래김,매출,20210902,152038,6660.0,012018_2494
33,20210902,12018,01,457,2,정상판매,1,8801104212694,12205.0,1.0,3680.0,3680.0,빙그레 굿모닝우유기획,매출,20210902,152038,6660.0,012018_2494
34,20210902,12018,05,231,3,정상판매,1,8801039939499,12301.0,2.0,2980.0,5960.0,해표 더고소한 파래김,매출,20210902,185158,74180.0,012018_25
35,20210902,12018,05,231,5,정상판매,1,2999000001262,40601.0,2.0,4980.0,9960.0,*의성햇사과/8입(1봉),매출,20210902,185158,74180.0,012018_25
36,20210902,12018,05,231,7,정상판매,1,2908990004443,30101.0,1.0,1980.0,1980.0,쌈배추(벌크)1통,매출,20210902,185158,74180.0,012018_25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968528,20220901,12018,7,167,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,125153,5000.0,012018_3736
4968529,20220901,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,125736,5000.0,012018_1636
4968531,20220901,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,142602,10000.0,012018_6700
4968532,20220901,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,162924,5000.0,012018_2764
4968533,20220901,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,162937,22600.0,012018_4787

In [20]:
b.isnull().sum()

SAL_DT             0
STR_CD             0
POS_NO             0
TRAN_NO            0
SEQ_NO             0
DESI_CNCL_TP_NM    0
SALE_RTN_SGN       0
PLU_CD             0
GDS_CLSS_CD        0
SALE_QTY           0
SALE_PRC           0
SALE_AMT           0
GDS_NM             0
SALE_KIND_TP_NM    0
REAL_SAL_DT        0
REAL_SAL_TTM       0
PAY_AMT            0
MSHP_ID            0
dtype: int64

In [34]:
c = b[['SAL_DT', 'MSHP_ID']]
c

           SAL_DT      MSHP_ID
32       20210902  012018_2494
33       20210902  012018_2494
34       20210902    012018_25
35       20210902    012018_25
36       20210902    012018_25
...           ...          ...
4968528  20220901  012018_3736
4968529  20220901  012018_1636
4968531  20220901  012018_6700
4968532  20220901  012018_2764
4968533  20220901  012018_4787

[4219589 rows x 2 columns]

In [35]:
c.head(300)

       SAL_DT       MSHP_ID
32   20210902   012018_2494
33   20210902   012018_2494
34   20210902     012018_25
35   20210902     012018_25
36   20210902     012018_25
37   20210902     012018_25
38   20210902     012018_25
39   20210902     012018_25
40   20210902     012018_25
41   20210902     012018_25
58   20210903   012018_4221
59   20210903   012018_4221
60   20210903   012018_4221
61   20210903   012018_4221
62   20210903   012018_4221
63   20210903   012018_4221
64   20210903   012018_4221
65   20210903   012018_4221
82   20210904   012018_3704
83   20210904   012018_3704
84   20210904   012018_3704
85   20210904   012018_3704
86   20210904   012018_3704
87   20210904   012018_5775
88   20210904   012018_5775
89   20210904   012018_5775
90   20210904   012018_5775
91   20210904   012018_5948
92   20210904   012018_5948
93   20210904   012018_5948
94   20210904   012018_5948
95   20210904   012018_5948
96   20210904   012018_5948
97   20210904   012018_5948
98   20210904   012018_5948
99   20210904   012018_5948
100  20210904   012018_5948
101  20210904   012018_5948
102  20210904   012018_5948
103  20210904   012018_5948
104  20210904   012018_5948
105  20210904   012018_6290
106  20210904   012018_6290
107  20210904   012018_6290
108  20210904   012018_6290
109  20210904   012018_6290
110  20210904   012018_6290
111  20210904   012018_6290
112  20210904   012018_6290
113  20210904   012018_6290
114  20210904   012018_6290
115  20210905   012018_2044
116  20210905   012018_1257
117  20210905   012018_1257
118  20210905   012018_1257
119  20210905   012018_1257
120  20210905   012018_1257
121  20210905   012018_1257
122  20210905   012018_1257
123  20210905   012018_1257
124  20210905   012018_1257
125  20210905   012018_1257
126  20210905   012018_1257
127  20210905   012018_1257
128  20210905   012018_1257
129  20210905   012018_1257
130  20210905   012018_1257
131  20210906    012018_458
132  20210906    012018_458
133  20210906    012018_458
134  20210906    012018_458
135  20210906    012018_458
136  20210906    012018_458
137  20210906   012018_3923
138  20210906   012018_3923
139  20210906   012018_3923
140  20210906   012018_3923
141  20210906   012018_3923
142  20210906   012018_3923
143  20210906   012018_3923
144  20210906   012018_3923
145  20210906   012018_3923
146  20210906   012018_3923
181  20210908   012018_1719
182  20210908   012018_1719
183  20210908   012018_1719
184  20210908   012018_1719
185  20210908   012018_1719
186  20210908   012018_1719
187  20210908   012018_1719
188  20210908   012018_1719
189  20210908   012018_1719
190  20210908   012018_1719
191  20210908   012018_2044
192  20210908   012018_2044
193  20210908   012018_2044
194  20210908   012018_2044
195  20210908   012018_2044
196  20210908   012018_2044
197  20210908   012018_5005
198  20210908   012018_5005
199  20210908   012018_5005
200  20210908   012018_5005
201  20210908   012018_5005
202  20210908   012018_5005
203  20210908   012018_5005
204  20210908   012018_5005
205  20210908   012018_5005
206  20210908   012018_5005
207  20210908   012018_5005
208  20210908   012018_5005
209  20210908   012018_5005
210  20210908   012018_5005
211  20210908   012018_5005
212  20210908   012018_5005
213  20210908   012018_5005
214  20210908   012018_5005
215  20210909   012018_9338
216  20210909   012018_9338
217  20210909   012018_9338
218  20210909   012018_9338
219  20210909   012018_9338
220  20210909   012018_9338
221  20210909   012018_9338
222  20210909   012018_9338
223  20210909   012018_9338
224  20210909   012018_9338
225  20210909   012018_9338
226  20210909   012018_9338
227  20210909   012018_9338
228  20210909   012018_9338
229  20210909   012018_9338
230  20210909   012018_9338
231  20210909   012018_9338
232  20210909   012018_9338
233  20210909   012018_9338
234  20210909   012018_9338
235  20210909   012018_9338
236  20210909   012018_9338
237  20210909   012018_9338
238  20210909   012018_9338
239  20210909   012018_1195
240  20210909   012018_1195
241  20210909   012018_8703
242  20210909   012018_8703
243  20210909   012018_8703
244  20210909   012018_8703
245  20210909   012018_8703
246  20210909   012018_8703
247  20210909   012018_8703
248  20210909   012018_8703
249  20210909   012018_8703
250  20210909   012018_8703
251  20210909   012018_8703
252  20210909   012018_8703
253  20210909   012018_8703
254  20210909   012018_8703
255  20210909   012018_8703
256  20210909   012018_8703
257  20210909   012018_8703
258  20210909   012018_8703
259  20210909   012018_8703
260  20210909   012018_8703
261  20210909   012018_8703
262  20210909   012018_8703
263  20210909   012018_8703
264  20210909   012018_8703
265  20210909   012018_8703
266  20210909   012018_8703
267  20210909   012018_8703
268  20210909   012018_8703
269  20210909   012018_8703
270  20210909   012018_8703
271  20210909   012018_8703
272  20210909   012018_8703
273  20210909   012018_8703
274  20210909   012018_8703
275  20210909   012018_8703
276  20210909   012018_8703
277  20210909   012018_8703
278  20210909   012018_8703
279  20210909   012018_8703
280  20210909   012018_8703
281  20210909   012018_8703
282  20210909   012018_8703
283  20210909   012018_9503
284  20210909   012018_9503
285  20210909   012018_9503
286  20210909   012018_9503
287  20210909   012018_9503
288  20210909   012018_9503
289  20210909   012018_9503
290  20210909   012018_9503
291  20210909   012018_9503
292  20210909   012018_9503
293  20210909   012018_9503
294  20210909   012018_9503
295  20210909   012018_9503
296  20210909   012018_9503
297  20210909   012018_9503
298  20210909   012018_9503
299  20210909   012018_9503
300  20210909   012018_9503
301  20210909   012018_9503
302  20210909   012018_9503
303  20210909   012018_9503
304  20210909   012018_9503
305  20210909   012018_9503
306  20210909   012018_9503
307  20210909   012018_9503
308  20210909   012018_9503
309  20210909   012018_9503
310  20210909   012018_9503
311  20210909   012018_9503
312  20210909   012018_9503
313  20210909   012018_9503
314  20210909   012018_9503
315  20210909   012018_9503
316  20210909   012018_9503
317  20210909   012018_9503
318  20210909   012018_9503
319  20210910    012018_332
320  20210910    012018_332
321  20210910   012018_9598
322  20210910   012018_9598
323  20210910   012018_9598
324  20210910   012018_9598
325  20210910   012018_9598
326  20210910   012018_9598
327  20210910    012018_860
328  20210910    012018_860
329  20210910    012018_860
330  20210910    012018_860
331  20210910    012018_860
332  20210910    012018_860
333  20210910    012018_860
334  20210910    012018_860
335  20210910    012018_860
336  20210910    012018_860
337  20210910    012018_860
338  20210910    012018_860
339  20210910    012018_860
340  20210910    012018_860
341  20210910    012018_860
342  20210910   012018_6290
343  20210910   012018_6290
344  20210910   012018_6290
345  20210910   012018_6290
346  20210910   012018_6290
347  20210910   012018_6290
348  20210910   012018_6290
349  20210910   012018_6290
350  20210910   012018_6290
351  20210910   012018_6290
352  20210910   012018_6290
353  20210910   012018_6290
354  20210910   012018_6290
355  20210910   012018_6290
356  20210910   012018_6290
357  20210910   012018_6290
358  20210910   012018_6290
359  20210910   012018_6290
360  20210910   012018_6290
361  20210911   012018_6035
362  20210911   012018_6035
363  20210911   012018_6035
364  20210911   012018_1152
365  20210911   012018_1152
366  20210911   012018_1152
367  20210912    012018_447
368  20210912    012018_447
369  20210912    012018_447
370  20210912    012018_447
371  20210912   012018_2837
372  20210912   012018_2837
373  20210912   012018_2837
374  20210912   012018_2837
375  20210912   012018_2837
376  20210912   012018_2837
377  20210912   012018_2837
378  20210912   012018_2837
379  20210912   012018_5826
380  20210912   012018_5826
381  20210912   012018_5826
382  20210912   012018_5826
383  20210912   012018_5826
384  20210912   012018_5826
385  20210912   012018_5826
386  20210912   012018_5826
387  20210912   012018_5826
388  20210912   012018_5826
389  20210912   012018_5826
390  20210912   012018_5826
391  20210912   012018_5826
392  20210912   012018_5826
393  20210912   012018_5826
394  20210912   012018_5826
395  20210912  012018_10584
396  20210912  012018_10584
397  20210912  012018_10584

In [5]:
d = b[['SAL_DT', 'GDS_NM', 'MSHP_ID']]
d

           SAL_DT         GDS_NM      MSHP_ID
32       20210902    해표 더고소한 파래김  012018_2494
33       20210902    빙그레 굿모닝우유기획  012018_2494
34       20210902    해표 더고소한 파래김    012018_25
35       20210902  *의성햇사과/8입(1봉)    012018_25
36       20210902      쌈배추(벌크)1통    012018_25
...           ...            ...          ...
4968528  20220901       햇배 4개/행사  012018_3736
4968529  20220901       햇배 4개/행사  012018_1636
4968531  20220901       햇배 4개/행사  012018_6700
4968532  20220901       햇배 4개/행사  012018_2764
4968533  20220901   청정원 올리브유 재래김  012018_4787

[4219589 rows x 3 columns]

In [6]:
d[d['MSHP_ID'] == '012018_2494']

           SAL_DT                GDS_NM      MSHP_ID
32       20210902           해표 더고소한 파래김  012018_2494
33       20210902           빙그레 굿모닝우유기획  012018_2494
2549     20211021           해표 더고소한 파래김  012018_2494
2550     20211021              검은콩깨보리건빵  012018_2494
2551     20211021               빙그레요구르트  012018_2494
...           ...                   ...          ...
4955029  20220612         *호박고구마 1봉(비닐)  012018_2494
4955823  20220613          *파프리카 2개(행사)  012018_2494
4964535  20220629          *초당옥수수 2개입/팩  012018_2494
4965298  20220708                부라보콘우유  012018_2494
4967668  20220728  *밤고구마(소)10kg/1박스(행사)  012018_2494

[593 rows x 3 columns]

In [7]:
e = b[['GDS_NM','MSHP_ID']]
e

                GDS_NM      MSHP_ID
32         해표 더고소한 파래김  012018_2494
33         빙그레 굿모닝우유기획  012018_2494
34         해표 더고소한 파래김    012018_25
35       *의성햇사과/8입(1봉)    012018_25
36           쌈배추(벌크)1통    012018_25
...                ...          ...
4968528       햇배 4개/행사  012018_3736
4968529       햇배 4개/행사  012018_1636
4968531       햇배 4개/행사  012018_6700
4968532       햇배 4개/행사  012018_2764
4968533   청정원 올리브유 재래김  012018_4787

[4219589 rows x 2 columns]

In [9]:
f = b[['MSHP_ID']]
f

             MSHP_ID
32       012018_2494
33       012018_2494
34         012018_25
35         012018_25
36         012018_25
...              ...
4968528  012018_3736
4968529  012018_1636
4968531  012018_6700
4968532  012018_2764
4968533  012018_4787

[4219589 rows x 1 columns]

In [12]:
# gmer = pd.merge(e,f,how='left', on='MSHP_ID')

In [16]:
# pd.set_option('display.max_row', 2000)

In [18]:
# gmer = pd.merge(e,f,how='right', on='MSHP_ID')

MemoryError: Unable to allocate 33.7 GiB for an array with shape (2, 2262979623) and data type object

In [19]:
# gmer = pd.merge(e,f,how='inner', on='MSHP_ID')

MemoryError: Unable to allocate 16.9 GiB for an array with shape (2262979623,) and data type int64

In [ ]:
# d랑 f랑 해보기 날짜까지

In [20]:
# gmer = pd.merge(e,f,how='outer', on='MSHP_ID')

MemoryError: Unable to allocate 16.9 GiB for an array with shape (2262979623,) and data type int64

In [21]:
# gmer = pd.merge(e,f,how='left', on='MSHP_ID')

MemoryError: Unable to allocate 16.9 GiB for an array with shape (2262979623,) and data type int64

In [ ]:
gmer.head(2000)

In [ ]:
#gmer = pd.merge(e,f,how='left', on='MSHP_ID')

In [ ]:
#gmer = pd.merge(e,f,how='inner', on='MSHP_ID')

In [ ]:
#gmer = pd.merge(e,f,how='outer', on='MSHP_ID')