In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''

In [2]:
# a 마트 gds+list+dtl
amartsum = pd.read_csv(base_path + 'amartsum.csv')
amartsum

C:\Users\min\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID
0,20210901,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,71138,9000000.0,NaN
1,20210901,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,71138,9000000.0,NaN
2,20210901,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,71138,9000000.0,NaN
3,20210901,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,71138,9000000.0,NaN
4,20210901,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,71138,9000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968529,20220901,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,125736,5000.0,012018_1636
4968530,20220901,12018,7,242,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,142401,5000.0,NaN
4968531,20220901,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,142602,10000.0,012018_6700
4968532,20220901,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,162924,5000.0,012018_2764
4968533,20220901,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,162937,22600.0,012018_4787

In [3]:
amartsum.SAL_DT = amartsum.SAL_DT.astype('str')

In [4]:
amartsum.REAL_SAL_DT = amartsum.REAL_SAL_DT.astype('str')

In [5]:
amartsum.REAL_SAL_TTM = amartsum.REAL_SAL_TTM.astype('str')

In [6]:
amartsum.SAL_DT = pd.to_datetime(amartsum.SAL_DT)

In [7]:
t1 = amartsum['REAL_SAL_TTM'].astype(str).str.zfill(6)
amartsum['REAL_SAL_TTM'] = pd.to_datetime(t1, format='%H%M%S').dt.time

print (amartsum)

            SAL_DT  STR_CD POS_NO  TRAN_NO  SEQ_NO DESI_CNCL_TP_NM  \
0       2021-09-01   12018     01        3       1            정상판매
1       2021-09-01   12018     01        3       2            정상판매
2       2021-09-01   12018     01        3       3            정상판매
3       2021-09-01   12018     01        3       4            정상판매
4       2021-09-01   12018     01        3       5            정상판매
...            ...     ...    ...      ...     ...             ...
4968529 2022-09-01   12018      7      175       1            정상판매
4968530 2022-09-01   12018      7      242       1            정상판매
4968531 2022-09-01   12018      7      245       1            정상판매
4968532 2022-09-01   12018      7      385       1            정상판매
4968533 2022-09-01   12018      1      354       1            정상판매

         SALE_RTN_SGN         PLU_CD  GDS_CLSS_CD  SALE_QTY  SALE_PRC  \
0                   1  8801039939499      12301.0     180.0    3000.0
1                   1  8801045312316      12101.0     360.0    1000.0
2                   1  8801045291314      12101.0     360.0    1000.0
3                   1  8803712127018      11363.0     180.0    2700.0
4                   1  8801045890333      12102.0     180.0    9500.0
...               ...            ...          ...       ...       ...
4968529             1  2999000035403      40602.0       1.0    5000.0
4968530             1  2999000035403      40602.0       1.0    5000.0
4968531             1  2999000035403      40602.0       2.0    5000.0
4968532             1  2999000035403      40602.0       1.0    5000.0
4968533             1  8801052098746      12211.0       2.0   11300.0

          SALE_AMT        GDS_NM SALE_KIND_TP_NM REAL_SAL_DT REAL_SAL_TTM  \
0         540000.0   해표 더고소한 파래김              매출    20210901     07:11:38
1         360000.0   오뚜기 3분쇠고기카레              매출    20210901     07:11:38
2         360000.0   오뚜기 3분쇠고기짜장              매출    20210901     07:11:38
3         486000.0        목우촌 뚝심              매출    20210901     07:11:38
4        1710000.0    오뚜기 맛있는밥기획              매출    20210901     07:11:38
...            ...           ...             ...         ...          ...
4968529     5000.0      햇배 4개/행사              매출    20220901     12:57:36
4968530     5000.0      햇배 4개/행사              매출    20220901     14:24:01
4968531    10000.0      햇배 4개/행사              매출    20220901     14:26:02
4968532     5000.0      햇배 4개/행사              매출    20220901     16:29:24
4968533    22600.0  청정원 올리브유 재래김              매출    20220901     16:29:37

           PAY_AMT      MSHP_ID
0        9000000.0          NaN
1        9000000.0          NaN
2        9000000.0          NaN
3        9000000.0          NaN
4        9000000.0          NaN
...            ...          ...
4968529     5000.0  012018_1636
4968530     5000.0          NaN
4968531    10000.0  012018_6700
4968532     5000.0  012018_2764
4968533    22600.0  012018_4787

[4968534 rows x 18 columns]

In [8]:
amartsum['hour'] = pd.to_datetime(amartsum['REAL_SAL_TTM'], format='%H:%M:%S').dt.hour
amartsum

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID,hour
0,2021-09-01,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,07:11:38,9000000.0,NaN,7
1,2021-09-01,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,07:11:38,9000000.0,NaN,7
2,2021-09-01,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,07:11:38,9000000.0,NaN,7
3,2021-09-01,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,07:11:38,9000000.0,NaN,7
4,2021-09-01,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,07:11:38,9000000.0,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968529,2022-09-01,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,12:57:36,5000.0,012018_1636,12
4968530,2022-09-01,12018,7,242,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,14:24:01,5000.0,NaN,14
4968531,2022-09-01,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,14:26:02,10000.0,012018_6700,14
4968532,2022-09-01,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,16:29:24,5000.0,012018_2764,16
4968533,2022-09-01,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,16:29:37,22600.0,012018_4787,16

In [56]:
amartsum.head(50)

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID,hour
0,2021-09-01,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,07:11:38,9000000.0,NaN,7
1,2021-09-01,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,07:11:38,9000000.0,NaN,7
2,2021-09-01,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,07:11:38,9000000.0,NaN,7
3,2021-09-01,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,07:11:38,9000000.0,NaN,7
4,2021-09-01,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,07:11:38,9000000.0,NaN,7
5,2021-09-01,12018,01,3,6,정상판매,1,8801007745671,12104.0,180.0,3600.0,648000.0,CJ 비비고소고기죽,매출,20210901,07:11:38,9000000.0,NaN,7
6,2021-09-01,12018,01,3,7,정상판매,1,8801007745718,12104.0,180.0,3600.0,648000.0,CJ 비비고버섯야채죽,매출,20210901,07:11:38,9000000.0,NaN,7
7,2021-09-01,12018,01,3,8,정상판매,1,8801043015264,11060.0,180.0,3500.0,630000.0,농심 짜파게티 멀티,매출,20210901,07:11:38,9000000.0,NaN,7
8,2021-09-01,12018,01,3,9,정상판매,1,8801045522234,11060.0,180.0,2500.0,450000.0,오뚜기 진라면 순한 멀티,매출,20210901,07:11:38,9000000.0,NaN,7
9,2021-09-01,12018,01,3,10,정상판매,1,8809398060045,10151.0,360.0,1800.0,648000.0,펭귄 황도,매출,20210901,07:11:38,9000000.0,NaN,7
10,2021-09-01,12018,01,3,11,정상판매,1,8801007561677,12101.0,180.0,2900.0,522000.0,비비고/미역국,매출,20210901,07:11:38,9000000.0,NaN,7
11,2021-09-01,12018,01,3,12,정상판매,1,8801007526515,12101.0,180.0,2900.0,522000.0,비비고/육개장,매출,20210901,07:11:38,9000000.0,NaN,7
12,2021-09-01,12018,01,3,13,정상판매,1,8801052040530,10152.0,180.0,2000.0,360000.0,종가집 볶음김치캔,매출,20210901,07:11:38,9000000.0,NaN,7
13,2021-09-01,12018,01,3,14,정상판매,1,8801052040523,10152.0,180.0,2000.0,360000.0,종가집 김치캔,매출,20210901,07:11:38,9000000.0,NaN,7
14,2021-09-01,12018,01,3,15,정상판매,1,2908990043152,29999.0,180.0,1200.0,216000.0,구호물품 포장박스,매출,20210901,07:11:38,9000000.0,NaN,7
15,2021-09-01,12018,01,3,16,정상판매,1,2908990043169,29999.0,180.0,3000.0,540000.0,구호물품 택배비,매출,20210901,07:11:38,9000000.0,NaN,7
16,2021-09-02,12018,01,15,1,정상판매,1,8801039939499,12301.0,110.0,3000.0,330000.0,해표 더고소한 파래김,매출,20210902,07:35:47,5500000.0,NaN,7
17,2021-09-02,12018,01,15,2,정상판매,1,8801045312316,12101.0,220.0,1000.0,220000.0,오뚜기 3분쇠고기카레,매출,20210902,07:35:47,5500000.0,NaN,7
18,2021-09-02,12018,01,15,3,정상판매,1,8801045291314,12101.0,220.0,1000.0,220000.0,오뚜기 3분쇠고기짜장,매출,20210902,07:35:47,5500000.0,NaN,7
19,2021-09-02,12018,01,15,4,정상판매,1,8803712127018,11363.0,110.0,2700.0,297000.0,목우촌 뚝심,매출,20210902,07:35:47,5500000.0,NaN,7
20,2021-09-02,12018,01,15,5,정상판매,1,8801045890333,12102.0,110.0,9500.0,1045000.0,오뚜기 맛있는밥기획,매출,20210902,07:35:47,5500000.0,NaN,7
21,2021-09-02,12018,01,15,6,정상판매,1,8801007745671,12104.0,110.0,3600.0,396000.0,CJ 비비고소고기죽,매출,20210902,07:35:47,5500000.0,NaN,7
22,2021-09-02,12018,01,15,7,정상판매,1,8801007745718,12104.0,110.0,3600.0,396000.0,CJ 비비고버섯야채죽,매출,20210902,07:35:47,5500000.0,NaN,7
23,2021-09-02,12018,01,15,8,정상판매,1,8801043015264,11060.0,110.0,3500.0,385000.0,농심 짜파게티 멀티,매출,20210902,07:35:47,5500000.0,NaN,7
24,2021-09-02,12018,01,15,9,정상판매,1,8801045522234,11060.0,110.0,2500.0,275000.0,오뚜기 진라면 순한 멀티,매출,20210902,07:35:47,5500000.0,NaN,7
25,2021-09-02,12018,01,15,10,정상판매,1,8809398060045,10151.0,220.0,1800.0,396000.0,펭귄 황도,매출,20210902,07:35:47,5500000.0,NaN,7
26,2021-09-02,12018,01,15,11,정상판매,1,8801007561677,12101.0,110.0,2900.0,319000.0,비비고/미역국,매출,20210902,07:35:47,5500000.0,NaN,7
27,2021-09-02,12018,01,15,12,정상판매,1,8801007526515,12101.0,110.0,2900.0,319000.0,비비고/육개장,매출,20210902,07:35:47,5500000.0,NaN,7
28,2021-09-02,12018,01,15,13,정상판매,1,8801052040530,10152.0,110.0,2000.0,220000.0,종가집 볶음김치캔,매출,20210902,07:35:47,5500000.0,NaN,7
29,2021-09-02,12018,01,15,14,정상판매,1,8801052040523,10152.0,110.0,2000.0,220000.0,종가집 김치캔,매출,20210902,07:35:47,5500000.0,NaN,7
30,2021-09-02,12018,01,15,15,정상판매,1,2908990043152,29999.0,110.0,1200.0,132000.0,구호물품 포장박스,매출,20210902,07:35:47,5500000.0,NaN,7
31,2021-09-02,12018,01,15,16,정상판매,1,2908990043169,29999.0,110.0,3000.0,330000.0,구호물품 택배비,매출,20210902,07:35:47,5500000.0,NaN,7
32,2021-09-02,12018,01,457,1,정상판매,1,8801039939499,12301.0,1.0,2980.0,2980.0,해표 더고소한 파래김,매출,20210902,15:20:38,6660.0,012018_2494,15
33,2021-09-02,12018,01,457,2,정상판매,1,8801104212694,12205.0,1.0,3680.0,3680.0,빙그레 굿모닝우유기획,매출,20210902,15:20:38,6660.0,012018_2494,15
34,2021-09-02,12018,05,231,3,정상판매,1,8801039939499,12301.0,2.0,2980.0,5960.0,해표 더고소한 파래김,매출,20210902,18:51:58,74180.0,012018_25,18
35,2021-09-02,12018,05,231,5,정상판매,1,2999000001262,40601.0,2.0,4980.0,9960.0,*의성햇사과/8입(1봉),매출,20210902,18:51:58,74180.0,012018_25,18
36,2021-09-02,12018,05,231,7,정상판매,1,2908990004443,30101.0,1.0,1980.0,1980.0,쌈배추(벌크)1통,매출,20210902,18:51:58,74180.0,012018_25,18
37,2021-09-02,12018,05,231,4,정상판매,1,2908990003866,40101.0,1.0,9800.0,9800.0,*성주꿀참외(특)/6입.1봉,매출,20210902,18:51:58,74180.0,012018_25,18
38,2021-09-02,12018,05,231,2,정상판매,1,351060,52599.0,1.0,13060.0,13060.0,대패삼겹살(수입),매출,20210902,18:51:58,74180.0,012018_25,18
39,2021-09-02,12018,05,231,10,정상판매,1,201447,40702.0,1.0,7980.0,7980.0,거봉포도,매출,20210902,18:51:58,74180.0,012018_25,18
40,2021-09-02,12018,05,231,6,정상판매,1,8801062890071,11502.0,1.0,3980.0,3980.0,롯데 마가렛트,매출,20210902,18:51:58,74180.0,012018_25,18
41,2021-09-02,12018,05,231,1,정상판매,1,8801045784205,10303.0,1.0,13500.0,13500.0,오뚜기 1등급란,매출,20210902,18:51:58,74180.0,012018_25,18
42,2021-09-03,12018,01,8,1,정상판매,1,8801039939499,12301.0,91.0,3000.0,273000.0,해표 더고소한 파래김,매출,20210903,07:39:08,4550000.0,NaN,7
43,2021-09-03,12018,01,8,2,정상판매,1,8801045312316,12101.0,182.0,1000.0,182000.0,오뚜기 3분쇠고기카레,매출,20210903,07:39:08,4550000.0,NaN,7
44,2021-09-03,12018,01,8,3,정상판매,1,8801045291314,12101.0,182.0,1000.0,182000.0,오뚜기 3분쇠고기짜장,매출,20210903,07:39:08,4550000.0,NaN,7
45,2021-09-03,12018,01,8,4,정상판매,1,8803712127018,11363.0,91.0,2700.0,245700.0,목우촌 뚝심,매출,20210903,07:39:08,4550000.0,NaN,7
46,2021-09-03,12018,01,8,5,정상판매,1,8801045890333,12102.0,91.0,9500.0,864500.0,오뚜기 맛있는밥기획,매출,20210903,07:39:08,4550000.0,NaN,7
47,2021-09-03,12018,01,8,6,정상판매,1,8801007745671,12104.0,91.0,3600.0,327600.0,CJ 비비고소고기죽,매출,20210903,07:39:08,4550000.0,NaN,7
48,2021-09-03,12018,01,8,7,정상판매,1,8801007745718,12104.0,91.0,3600.0,327600.0,CJ 비비고버섯야채죽,매출,20210903,07:39:08,4550000.0,NaN,7
49,2021-09-03,12018,01,8,8,정상판매,1,8801043015264,11060.0,91.0,3500.0,318500.0,농심 짜파게티 멀티,매출,20210903,07:39:08,4550000.0,NaN,7

In [59]:
amartsum.sort_values('SALE_QTY', ascending=False).head(50)

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID,hour
7440,2022-02-17,12018,01,5,5,정상판매,1,8801123602117,11373.0,2295.0,1600.0,3672000.0,롯데 국산햄로스팜,매출,20220217,07:44:27,38250000.0,NaN,7
7359,2022-02-15,12018,01,3,5,정상판매,1,8801123602117,11373.0,1617.0,1600.0,2587200.0,롯데 국산햄로스팜,매출,20220215,07:41:41,26950000.0,NaN,7
7439,2022-02-17,12018,01,5,15,정상판매,1,8801047825050,11360.0,1530.0,1700.0,2601000.0,동원참치기획,매출,20220217,07:44:27,38250000.0,NaN,7
7434,2022-02-17,12018,01,5,11,정상판매,1,8809398060045,10151.0,1530.0,1500.0,2295000.0,펭귄 황도,매출,20220217,07:44:27,38250000.0,NaN,7
7428,2022-02-17,12018,01,5,4,정상판매,1,8801045291314,12101.0,1530.0,1000.0,1530000.0,오뚜기 3분쇠고기짜장,매출,20220217,07:44:27,38250000.0,NaN,7
7427,2022-02-17,12018,01,5,3,정상판매,1,8801045312316,12101.0,1530.0,1000.0,1530000.0,오뚜기 3분쇠고기카레,매출,20220217,07:44:27,38250000.0,NaN,7
6726,2022-01-25,12018,02,3,4,정상판매,1,8801123602117,11373.0,1404.0,1600.0,2246400.0,롯데 국산햄로스팜,매출,20220125,07:39:34,23400000.0,NaN,7
4858703,2021-10-18,12018,07,393,1,정상판매,-1,8801074802321,12550.0,1361.0,2100.0,2858100.0,요리가맛있는당면500g,매출,20211018,18:14:24,2858100.0,012018_2836,18
4858702,2021-10-18,12018,07,392,1,정상판매,1,8801074802321,12550.0,1361.0,2100.0,2858100.0,요리가맛있는당면500g,매출,20211018,18:14:09,2858100.0,012018_2836,18
6741,2022-01-26,12018,01,6,4,정상판매,1,8801123602117,11373.0,1119.0,1600.0,1790400.0,롯데 국산햄로스팜,매출,20220126,07:48:15,18650000.0,NaN,7
1773,2021-10-13,12018,01,9,2,정상판매,1,8801045312316,12101.0,1096.0,1000.0,1096000.0,오뚜기 3분쇠고기카레,매출,20211013,08:01:53,27400000.0,NaN,8
1781,2021-10-13,12018,01,9,15,정상판매,1,8809398060045,10151.0,1096.0,1800.0,1972800.0,펭귄 황도,매출,20211013,08:01:53,27400000.0,NaN,8
1774,2021-10-13,12018,01,9,3,정상판매,1,8801045291314,12101.0,1096.0,1000.0,1096000.0,오뚜기 3분쇠고기짜장,매출,20211013,08:01:53,27400000.0,NaN,8
7353,2022-02-15,12018,01,3,11,정상판매,1,8809398060045,10151.0,1078.0,1500.0,1617000.0,펭귄 황도,매출,20220215,07:41:41,26950000.0,NaN,7
7346,2022-02-15,12018,01,3,3,정상판매,1,8801045312316,12101.0,1078.0,1000.0,1078000.0,오뚜기 3분쇠고기카레,매출,20220215,07:41:41,26950000.0,NaN,7
7347,2022-02-15,12018,01,3,4,정상판매,1,8801045291314,12101.0,1078.0,1000.0,1078000.0,오뚜기 3분쇠고기짜장,매출,20220215,07:41:41,26950000.0,NaN,7
7358,2022-02-15,12018,01,3,15,정상판매,1,8801047825050,11360.0,1078.0,1700.0,1832600.0,동원참치기획,매출,20220215,07:41:41,26950000.0,NaN,7
4288494,2022-04-19,12018,01,148,1,정상판매,1,2908990004566,30702.0,1000.0,2500.0,2500000.0,*양파(소),매출,20220419,11:06:58,2500000.0,NaN,11
4288495,2022-04-19,12018,01,149,1,정상판매,-1,2908990004566,30702.0,1000.0,2500.0,2500000.0,*양파(소),매출,20220419,11:07:14,2500000.0,NaN,11
7086,2022-02-11,12018,01,9,4,정상판매,1,8801123602117,11373.0,984.0,1600.0,1574400.0,롯데 국산햄로스팜,매출,20220211,07:42:20,16400000.0,NaN,7
4987,2021-12-22,12018,01,13,10,정상판매,1,8801052066127,12101.0,976.0,1100.0,1073600.0,청정원 한우곰탕,매출,20211222,07:38:40,24400000.0,NaN,7
4976,2021-12-22,12018,01,13,2,정상판매,1,8801045312316,12101.0,976.0,1000.0,976000.0,오뚜기 3분쇠고기카레,매출,20211222,07:38:40,24400000.0,NaN,7
4977,2021-12-22,12018,01,13,3,정상판매,1,8801045291314,12101.0,976.0,1000.0,976000.0,오뚜기 3분쇠고기짜장,매출,20211222,07:38:40,24400000.0,NaN,7
4984,2021-12-22,12018,01,13,13,정상판매,1,8809398060045,10151.0,976.0,1800.0,1756800.0,펭귄 황도,매출,20211222,07:38:40,24400000.0,NaN,7
5353,2022-01-04,12018,01,5,3,정상판매,1,8801045291314,12101.0,966.0,1000.0,966000.0,오뚜기 3분쇠고기짜장,매출,20220104,07:33:10,24150000.0,NaN,7
5363,2022-01-04,12018,01,5,10,정상판매,1,8801052066127,12101.0,966.0,1100.0,1062600.0,청정원 한우곰탕,매출,20220104,07:33:10,24150000.0,NaN,7
5360,2022-01-04,12018,01,5,13,정상판매,1,8809398060045,10151.0,966.0,1800.0,1738800.0,펭귄 황도,매출,20220104,07:33:10,24150000.0,NaN,7
5352,2022-01-04,12018,01,5,2,정상판매,1,8801045312316,12101.0,966.0,1000.0,966000.0,오뚜기 3분쇠고기카레,매출,20220104,07:33:10,24150000.0,NaN,7
4372,2021-11-30,12018,01,4,3,정상판매,1,8801045291314,12101.0,960.0,1000.0,960000.0,오뚜기 3분쇠고기짜장,매출,20211130,07:34:07,24000000.0,NaN,7
4379,2021-11-30,12018,01,4,13,정상판매,1,8809398060045,10151.0,960.0,1800.0,1728000.0,펭귄 황도,매출,20211130,07:34:07,24000000.0,NaN,7
4371,2021-11-30,12018,01,4,2,정상판매,1,8801045312316,12101.0,960.0,1000.0,960000.0,오뚜기 3분쇠고기카레,매출,20211130,07:34:07,24000000.0,NaN,7
4382,2021-11-30,12018,01,4,10,정상판매,1,8801052066127,12101.0,960.0,1100.0,1056000.0,청정원 한우곰탕,매출,20211130,07:34:07,24000000.0,NaN,7
6545,2022-01-21,12018,01,4,4,정상판매,1,8801123602117,11373.0,948.0,1600.0,1516800.0,롯데 국산햄로스팜,매출,20220121,07:36:11,15800000.0,NaN,7
6714,2022-01-25,12018,02,3,3,정상판매,1,8801045291314,12101.0,936.0,1000.0,936000.0,오뚜기 3분쇠고기짜장,매출,20220125,07:39:34,23400000.0,NaN,7
6720,2022-01-25,12018,02,3,10,정상판매,1,8809398060045,10151.0,936.0,1500.0,1404000.0,펭귄 황도,매출,20220125,07:39:34,23400000.0,NaN,7
6725,2022-01-25,12018,02,3,14,정상판매,1,8801047825050,11360.0,936.0,1700.0,1591200.0,동원참치기획,매출,20220125,07:39:34,23400000.0,NaN,7
6713,2022-01-25,12018,02,3,2,정상판매,1,8801045312316,12101.0,936.0,1000.0,936000.0,오뚜기 3분쇠고기카레,매출,20220125,07:39:34,23400000.0,NaN,7
4877,2021-12-21,12018,01,14,13,정상판매,1,8809398060045,10151.0,864.0,1800.0,1555200.0,펭귄 황도,매출,20211221,08:00:47,21600000.0,NaN,8
4880,2021-12-21,12018,01,14,10,정상판매,1,8801052066127,12101.0,864.0,1100.0,950400.0,청정원 한우곰탕,매출,20211221,08:00:47,21600000.0,NaN,8
4870,2021-12-21,12018,01,14,3,정상판매,1,8801045291314,12101.0,864.0,1000.0,864000.0,오뚜기 3분쇠고기짜장,매출,20211221,08:00:47,21600000.0,NaN,8
4869,2021-12-21,12018,01,14,2,정상판매,1,8801045312316,12101.0,864.0,1000.0,864000.0,오뚜기 3분쇠고기카레,매출,20211221,08:00:47,21600000.0,NaN,8
6624,2022-01-22,12018,02,3,4,정상판매,1,8801123602117,11373.0,828.0,1600.0,1324800.0,롯데 국산햄로스팜,매출,20220122,07:54:58,13800000.0,NaN,7
7128,2022-02-12,12018,01,6,4,정상판매,1,8801123602117,11373.0,804.0,1600.0,1286400.0,롯데 국산햄로스팜,매출,20220212,07:35:46,13400000.0,NaN,7
7430,2022-02-17,12018,01,5,7,정상판매,1,8801007745671,12104.0,765.0,2700.0,2065500.0,CJ 비비고소고기죽,매출,20220217,07:44:27,38250000.0,NaN,7
7433,2022-02-17,12018,01,5,10,정상판매,1,8801045522234,11060.0,765.0,2700.0,2065500.0,오뚜기 진라면 순한 멀티,매출,20220217,07:44:27,38250000.0,NaN,7
7436,2022-02-17,12018,01,5,16,정상판매,1,2908990043169,29999.0,765.0,4000.0,3060000.0,구호물품 택배비,매출,20220217,07:44:27,38250000.0,NaN,7
7429,2022-02-17,12018,01,5,6,정상판매,1,8801045890333,12102.0,765.0,9200.0,7038000.0,오뚜기 맛있는밥기획,매출,20220217,07:44:27,38250000.0,NaN,7
7426,2022-02-17,12018,01,5,1,정상판매,1,8801039939499,12301.0,765.0,3000.0,2295000.0,해표 더고소한 파래김,매출,20220217,07:44:27,38250000.0,NaN,7
7435,2022-02-17,12018,01,5,14,정상판매,1,8801052040523,10152.0,765.0,2000.0,1530000.0,종가집 김치캔,매출,20220217,07:44:27,38250000.0,NaN,7
7431,2022-02-17,12018,01,5,8,정상판매,1,8801007745718,12104.0,765.0,2700.0,2065500.0,CJ 비비고버섯야채죽,매출,20220217,07:44:27,38250000.0,NaN,7

In [61]:
amartsum.isnull().sum()

SAL_DT                  0
STR_CD                  0
POS_NO                  0
TRAN_NO                 0
SEQ_NO                  0
DESI_CNCL_TP_NM         0
SALE_RTN_SGN            0
PLU_CD                  0
GDS_CLSS_CD             0
SALE_QTY                0
SALE_PRC                0
SALE_AMT                0
GDS_NM                  0
SALE_KIND_TP_NM         0
REAL_SAL_DT             0
REAL_SAL_TTM            0
PAY_AMT                 0
MSHP_ID            688555
hour                    0
dtype: int64

In [9]:
amartsum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4968534 entries, 0 to 4968533
Data columns (total 19 columns):
 #   Column           Dtype
---  ------           -----
 0   SAL_DT           datetime64[ns]
 1   STR_CD           int64
 2   POS_NO           object
 3   TRAN_NO          int64
 4   SEQ_NO           int64
 5   DESI_CNCL_TP_NM  object
 6   SALE_RTN_SGN     int64
 7   PLU_CD           int64
 8   GDS_CLSS_CD      float64
 9   SALE_QTY         float64
 10  SALE_PRC         float64
 11  SALE_AMT         float64
 12  GDS_NM           object
 13  SALE_KIND_TP_NM  object
 14  REAL_SAL_DT      object
 15  REAL_SAL_TTM     object
 16  PAY_AMT          float64
 17  MSHP_ID          object
 18  hour             int64
dtypes: datetime64[ns](1), float64(5), int64(6), object(7)
memory usage: 720.2+ MB

In [10]:
amartsum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4968534 entries, 0 to 4968533
Data columns (total 19 columns):
 #   Column           Dtype
---  ------           -----
 0   SAL_DT           datetime64[ns]
 1   STR_CD           int64
 2   POS_NO           object
 3   TRAN_NO          int64
 4   SEQ_NO           int64
 5   DESI_CNCL_TP_NM  object
 6   SALE_RTN_SGN     int64
 7   PLU_CD           int64
 8   GDS_CLSS_CD      float64
 9   SALE_QTY         float64
 10  SALE_PRC         float64
 11  SALE_AMT         float64
 12  GDS_NM           object
 13  SALE_KIND_TP_NM  object
 14  REAL_SAL_DT      object
 15  REAL_SAL_TTM     object
 16  PAY_AMT          float64
 17  MSHP_ID          object
 18  hour             int64
dtypes: datetime64[ns](1), float64(5), int64(6), object(7)
memory usage: 720.2+ MB

In [11]:
amartsum

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,GDS_NM,SALE_KIND_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,PAY_AMT,MSHP_ID,hour
0,2021-09-01,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,해표 더고소한 파래김,매출,20210901,07:11:38,9000000.0,NaN,7
1,2021-09-01,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기카레,매출,20210901,07:11:38,9000000.0,NaN,7
2,2021-09-01,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,오뚜기 3분쇠고기짜장,매출,20210901,07:11:38,9000000.0,NaN,7
3,2021-09-01,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,목우촌 뚝심,매출,20210901,07:11:38,9000000.0,NaN,7
4,2021-09-01,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,오뚜기 맛있는밥기획,매출,20210901,07:11:38,9000000.0,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968529,2022-09-01,12018,7,175,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,12:57:36,5000.0,012018_1636,12
4968530,2022-09-01,12018,7,242,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,14:24:01,5000.0,NaN,14
4968531,2022-09-01,12018,7,245,1,정상판매,1,2999000035403,40602.0,2.0,5000.0,10000.0,햇배 4개/행사,매출,20220901,14:26:02,10000.0,012018_6700,14
4968532,2022-09-01,12018,7,385,1,정상판매,1,2999000035403,40602.0,1.0,5000.0,5000.0,햇배 4개/행사,매출,20220901,16:29:24,5000.0,012018_2764,16
4968533,2022-09-01,12018,1,354,1,정상판매,1,8801052098746,12211.0,2.0,11300.0,22600.0,청정원 올리브유 재래김,매출,20220901,16:29:37,22600.0,012018_4787,16

In [51]:
amartsum['GDS_CLSS_CD'].value_counts()

30201.0     308741
30101.0     260754
30702.0     181424
11502.0     179839
159999.0    158610
             ...
93004.0          7
12900.0          5
91117.0          2
11364.0          2
91102.0          1
Name: GDS_CLSS_CD, Length: 330, dtype: int64

In [70]:
test1 = amartsum.groupby('hour')['GDS_NM'].count()
test1

hour
5         23
6       2957
7      17734
8      50708
9     132917
10    280625
11    373160
12    391502
13    402508
14    442707
15    522335
16    568225
17    555699
18    499291
19    350578
20    259178
21    118387
Name: GDS_NM, dtype: int64

## a마트의 카테고리도 추가한 test 데이터

In [48]:
test = amartsum.groupby(['SAL_DT', 'TRAN_NO', 'hour', 'SALE_AMT','GDS_CLSS_CD'])['GDS_NM'].apply(list)
test

SAL_DT      TRAN_NO  hour  SALE_AMT  GDS_CLSS_CD
2021-09-01  1        10    1000.0    30201.0                     [*청양고추(소)]
                           1280.0    30702.0                       [*대파 1단]
                           2500.0    30201.0        [*꽈리고추 (500g), *백오이 3개]
                           2850.0    12560.0                    [CJ 안심김밥맛살]
                           2980.0    30702.0                       [*양파(소)]
                                                             ...
2022-09-01  689      21    12450.0   20901.0                    [죽염 시린고 치약]
            690      21    1200.0    12573.0               [CJ 양념이잘배는찌개두부 ]
            691      21    9800.0    40601.0                      [홍로사과/8개]
            692      21    1950.0    30201.0                      [*단호박 1개]
                           11800.0   30101.0                      [*청상추 1봉]
Name: GDS_NM, Length: 4774183, dtype: object

In [49]:
test = test.to_frame()
test

                                                               GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT GDS_CLSS_CD
2021-09-01 1       10   1000.0   30201.0                   [*청양고추(소)]
                        1280.0   30702.0                     [*대파 1단]
                        2500.0   30201.0      [*꽈리고추 (500g), *백오이 3개]
                        2850.0   12560.0                  [CJ 안심김밥맛살]
                        2980.0   30702.0                     [*양파(소)]
...                                                               ...
2022-09-01 689     21   12450.0  20901.0                  [죽염 시린고 치약]
           690     21   1200.0   12573.0             [CJ 양념이잘배는찌개두부 ]
           691     21   9800.0   40601.0                    [홍로사과/8개]
           692     21   1950.0   30201.0                    [*단호박 1개]
                        11800.0  30101.0                    [*청상추 1봉]

[4774183 rows x 1 columns]

In [12]:
amartsumgr1 = amartsum.groupby(['SAL_DT', 'TRAN_NO', 'hour', 'SALE_AMT'])['GDS_NM'].apply(list)
amartsumgr1

SAL_DT      TRAN_NO  hour  SALE_AMT
2021-09-01  1        10    1000.0                   [*청양고추(소)]
                           1280.0                     [*대파 1단]
                           2500.0      [*꽈리고추 (500g), *백오이 3개]
                           2850.0                  [CJ 안심김밥맛살]
                           2980.0                     [*양파(소)]
                                                ...
2022-09-01  689      21    12450.0                 [죽염 시린고 치약]
            690      21    1200.0             [CJ 양념이잘배는찌개두부 ]
            691      21    9800.0                    [홍로사과/8개]
            692      21    1950.0                    [*단호박 1개]
                           11800.0                   [*청상추 1봉]
Name: GDS_NM, Length: 4495149, dtype: object

In [13]:
# amartsumgr1.to_csv('amartsumgr1.csv', index = False)

In [14]:
amartsumgr1.head(30)

SAL_DT      TRAN_NO  hour  SALE_AMT
2021-09-01  1        10    1000.0                                          [*청양고추(소)]
                           1280.0                                            [*대파 1단]
                           2500.0                             [*꽈리고추 (500g), *백오이 3개]
                           2850.0                                         [CJ 안심김밥맛살]
                           2980.0                                            [*양파(소)]
                           3750.0                                         [농심 신라면 멀티]
                           4890.0                                         [오리온 후레쉬베리]
                           5980.0                                      [롯데 카스타드 오리지날]
                           19800.0                                    [*송산포도 3kg/1박스]
            2        10    1000.0                                 [*청양고추(소), 팽이버섯 1봉]
                           1300.0                                          [코멕스 고무장갑]
                           1580.0                                      [청정원 숨쉬는전통콩나물]
                           1920.0                                        [더건강한 샌드위치햄]
                           1980.0               [쌈배추(벌크)1통, *청양고추 1k, 풀무원 김밥김, 가지 1봉]
                           2850.0                                         [CJ 안심김밥맛살]
                           3050.0                                          [청정원 연와사비]
                           3280.0                                       [삼양라면 매운맛 멀티]
                           3400.0                                         [농심 육개장사발면]
                           3580.0                                      [청정원 담백건강한베이컨]
                           4500.0                                       [남양 GT고소한저지방]
                           7800.0                                          [CJ비비고왕교자]
                           12000.0                                          [한우양지국거리]
            3        6     400.0                                          [롯데 레쓰비마일드]
                     7     990.0                                          [동원 골든스위트콘]
                           2150.0                                           [청정원 맛소금]
                           216000.0                                       [구호물품 포장박스]
                           360000.0    [오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 종가집 볶음김치캔, 종가집 김치캔]
                           450000.0                                   [오뚜기 진라면 순한 멀티]
                           486000.0                                          [목우촌 뚝심]
                           522000.0                              [비비고/미역국 , 비비고/육개장 ]
Name: GDS_NM, dtype: object

In [15]:
amartsumgr1 = amartsumgr1.to_frame()
amartsumgr1

                                                   GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 1       10   1000.0                 [*청양고추(소)]
                        1280.0                   [*대파 1단]
                        2500.0    [*꽈리고추 (500g), *백오이 3개]
                        2850.0                [CJ 안심김밥맛살]
                        2980.0                   [*양파(소)]
...                                                   ...
2022-09-01 689     21   12450.0               [죽염 시린고 치약]
           690     21   1200.0           [CJ 양념이잘배는찌개두부 ]
           691     21   9800.0                  [홍로사과/8개]
           692     21   1950.0                  [*단호박 1개]
                        11800.0                 [*청상추 1봉]

[4495149 rows x 1 columns]

In [16]:
amartsumgr1

                                                   GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 1       10   1000.0                 [*청양고추(소)]
                        1280.0                   [*대파 1단]
                        2500.0    [*꽈리고추 (500g), *백오이 3개]
                        2850.0                [CJ 안심김밥맛살]
                        2980.0                   [*양파(소)]
...                                                   ...
2022-09-01 689     21   12450.0               [죽염 시린고 치약]
           690     21   1200.0           [CJ 양념이잘배는찌개두부 ]
           691     21   9800.0                  [홍로사과/8개]
           692     21   1950.0                  [*단호박 1개]
                        11800.0                 [*청상추 1봉]

[4495149 rows x 1 columns]

In [17]:
targer_month = 9
amartsumgr1.query('SAL_DT.dt.month == @targer_month')

                                                   GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 1       10   1000.0                 [*청양고추(소)]
                        1280.0                   [*대파 1단]
                        2500.0    [*꽈리고추 (500g), *백오이 3개]
                        2850.0                [CJ 안심김밥맛살]
                        2980.0                   [*양파(소)]
...                                                   ...
2022-09-01 689     21   12450.0               [죽염 시린고 치약]
           690     21   1200.0           [CJ 양념이잘배는찌개두부 ]
           691     21   9800.0                  [홍로사과/8개]
           692     21   1950.0                  [*단호박 1개]
                        11800.0                 [*청상추 1봉]

[431269 rows x 1 columns]

In [18]:
targer_month = 10
amartsumgr1.query('SAL_DT.dt.month == @targer_month')

                                                  GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-10-01 1       10   850.0                [농심 육개장사발면]
                        890.0               [농심 튀김우동큰사발]
                        980.0     [*수입산)브로컬리 2송이구입시(행사)]
                        990.0           [CJ 양념이잘배는찌개두부 ]
                        1000.0         [*부추 1단, *백오이 3개]
...                                                  ...
2021-10-31 638     21   5480.0            [롯데 맛있는비엔나소시지]
                        10200.0               [양념 목살왕구이]
           639     21   980.0                 [*아보카도/1개]
                        2980.0             [*델몬트바나나/1송이]
           640     21   1750.0             [삼립 아침엔밀크토스트]

[385341 rows x 1 columns]

In [19]:
targer_month = 11
amartsumgr1.query('SAL_DT.dt.month == @targer_month')

                                                GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-11-01 1       9    0.0       [백설/요리올리고당, 동원 카놀라유]
                        1100.0                [초야마늘가루]
                        1200.0                   [순두부]
                        1500.0       [*무우 1개(봉)(투명비닐)]
                        1980.0    [남양 이오기획, *하우스팩귤/1팩]
...                                                ...
2021-11-30 528     20   5000.0           [*감귤(벌크)/13개]
           529     20   3480.0                 [코카 순수]
                        14800.0         [*토마토/5kg/1박스]
           530     20   1250.0                [농심꿀꽈배기]
           531     20   6980.0        [*감귤(2S)5kg/1박스]

[364804 rows x 1 columns]

In [20]:
amartsumgr1.query('SAL_DT.dt.dayofweek == 0') # 월

                                                       GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-06 1       11   1350.0    [서울 비요뜨 초코팝, 서울 비요뜨 초코크리스피]
                        2500.0                      [백설 갈색설탕]
                        2980.0                       [*양파(소)]
                        3980.0                     [송학 감자수제비]
                        4380.0                   [오뚜기 진짬뽕 멀티]
...                                                       ...
2022-08-29 658     21   1000.0                       [서주 빵뚜르]
                        1200.0                        [바밤바샌드]
           659     21   1250.0                [*수입산)브로컬리 1송이]
                        3950.0                      [*청상추 1봉]
           660     21   10850.0                    [농심 우와한콩칩]

[618767 rows x 1 columns]

In [1]:
amartsumgr1.query('SAL_DT.dt.dayofweek == 4')

NameError: name 'amartsumgr1' is not defined

In [22]:
amartsumgr1.query('SAL_DT.dt.dayofweek == 5')

                                                        GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-04 1       10   1980.0                           [죠리퐁]
                        2480.0    [남양 프로바이오틱 사과, 남양 프로바이오틱 포도]
                        3980.0                   [빙그레 바나나우유기획]
                        4900.0                    [CJ비비고/사골곰탕]
                        5960.0                      [CJ명가 재래김]
...                                                        ...
2022-08-27 624     21   2560.0                    [콘트라베이스디카페인]
                        2980.0                    [해태 스낵4번들기획]
                        3480.0                        [삼립 보름달]
                        4240.0                      [롯데 미니크런키]
           625     21   4500.0                      [*청양고추 1k]

[757202 rows x 1 columns]

In [23]:
amartsumgr1.query('SAL_DT.dt.dayofweek == 6') # 일

                                                GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-05 1       11   980.0        [*무우 1개(봉)(투명비닐)]
                        990.0           [청정원 숨쉬는전통콩나물]
                        1480.0                [*대파 1단]
                        2850.0         [오뚜기 진라면 매운 멀티]
                        3960.0         [CJ 명가김 재래김 식탁]
...                                                ...
2022-08-28 685     21   3680.0          [농심 사천짜파게티 멀티]
                        3980.0               [코카콜라 제로]
           686     21   2600.0    [오뚜기 쉐이크핫케이크믹스 오리지널]
                        2900.0                 [서울 우유]
                        3480.0             [삼립 따베패스츄리]

[745108 rows x 1 columns]

## 이 부분은 내가 임의로 정하겠음.
### 오전 7시부터 찍혀있던걸로 기억하는데 6시를 기준으로
### 오전 6시 ~ 오전 10시 : 이른 오전
### 오전 10시 ~ 오후 2시 : 이른 오후
### 오후 2시 ~ 오후 7시 : 저녁 
###  오후 7시 ~ 마감시간 : 늦은 저녁

## 이렇게 예상하는 이유는 해당 시간에 대하여 판매를 기대하는 상품이 다를 것임. 예상되는 판매내역. 
## 아침(빵이나 유제품류, 달걀, 채소) 점심(일반적인 장 볼 때 제품)
## 저녁(저녁거리 및 주류) , 밤(주류, 안주거리 혹은 다음날 아침거리)

In [62]:
# pd.set_option('display.max_row', 300)

In [64]:
amartsumgr1.query('hour == 6')

                                         GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 3       6    400.0       [롯데 레쓰비마일드]
           4       6    1900.0        [진주 천하장사]
2021-09-02 3       6    400.0       [롯데 레쓰비마일드]
           4       6    990.0     [풀무원  소가찌개두부]
                        1500.0          [공주알밤술]
...                                         ...
2022-09-01 7       6    450.0       [롯데 레쓰비마일드]
           8       6    5200.0     [빙그레 바나나맛우유]
           9       6    3600.0     [해태 구론산스파클링]
           10      6    2700.0         [강릉초당두부]
                        5480.0      [청정원 장아찌소스]

[2810 rows x 1 columns]

In [ ]:
amartsumgr1.query('hour == 5')

In [68]:
amartsumgr1.query('hour == 6').head(300)

                                                              GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    1900.0                             [진주 천하장사]
2021-09-02 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    990.0                          [풀무원  소가찌개두부]
                        1500.0                               [공주알밤술]
           5       6    2580.0                          [롯데 자일리톨 리필]
                        6150.0                            [과탄산소다표백제]
           6       6    2700.0                              [강릉초당두부]
                        5000.0                         [풀무원 씻어나온콩나물]
           7       6    1700.0                               [서울 우유]
           8       6    990.0                             [대림 구운마늘햄]
                        1500.0                   [행복한콩/2가지로만 국산콩부침용]
                        1920.0                        [CJ 더건강한햄의성마늘]
                        9800.0                      [*햇홍로사과/8개/8개1봉]
2021-09-03 3       6    1960.0                           [서울 요구르트제로]
                        3000.0                          [CJ 비비고단호박죽]
           4       6    400.0                            [롯데 레쓰비마일드]
                        2500.0                          [*꽈리고추(소)1봉]
                        12490.0                                 [연근]
           6       6    980.0                             [동원 지중해황도]
                        2000.0                           [롯데 레쓰비마일드]
           7       6    2500.0                     [삼립 아침미소토스트앤샌드위치]
2021-09-04 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    990.0                         [종가집 콩이가득부침두부]
           5       6    5000.0                               [서울 우유]
2021-09-05 3       6    1500.0                           [아삭이고추(2팩)]
           4       6    2500.0                                  [가지]
                        3980.0                         [두번달여더진한 진간장]
                        8900.0                             [토속대란 1판]
           5       6    790.0                            [*느타리버섯 2팩]
                        990.0                       [CJ 양념이잘배는찌개두부 ]
                        2980.0                          [**인큐애호박 1개]
                        3300.0                            [서울 목장의우유]
2021-09-06 3       6    1200.0                     [롯데 칸타타 아이스아메리카노]
                        1400.0                           [푸드마크 암반얼음]
                        4980.0                         [*양배추(4*5)1망]
           4       6    4980.0                                [명품사과]
           5       6    2960.0                     [*무우 1개(봉)(투명비닐)]
2021-09-07 3       6    400.0                            [롯데 레쓰비마일드]
                        9960.0                                [장어탕 ]
           4       6    1000.0                           [다방커피 헤이즐럿]
           5       6    7700.0                          [포스트 현미그래놀라]
2021-09-08 3       6    400.0                            [롯데 레쓰비마일드]
                        990.0                       [CJ 양념이잘배는찌개두부 ]
           4       6    1980.0                           [대림 신선한콩두부]
                        2980.0                        [청정원 직화파기름굴소스]
                        4850.0                       [CJ 콩기름 (2개한정)]
2021-09-09 3       6    2250.0                                [박카스F]
           4       6    400.0                            [롯데 레쓰비마일드]
           5       6    980.0                             [동원 지중해황도]
           6       6    1960.0                            [동원 지중해황도]
           7       6    1000.0                         [롯데 레쓰비그란데라떼]
           8       6    2450.0                            [CJ백설 흑설탕]
                        2500.0                            [*청양고추 1k]
                        5600.0                            [청정원 전통쌀엿]
           9       6    4850.0                         [오뚜기 옛날참기름 캔]
           10      6    980.0                            [서울 요구르트제로]
                        2700.0                               [서울 우유]
           11      6    2350.0                 [CJ행복한콩/2가지로만 국산콩찌개용]
                        2950.0                           [장가가는마된장찌개]
           12      6    3600.0                      [롯데 스카시 오렌지100%]
                        16500.0                        [동서 맥심모카골드믹스]
2021-09-10 3       6    400.0                            [롯데 레쓰비마일드]
                        12240.0                          [한우불고기(우둔)]
           4       6    1960.0                          [롯데 칸타타 블렌드]
           5       6    1980.0                           [오뚜기 옛날육개장]
           6       6    750.0                          [롯데 레쓰비 연유커피]
                        2280.0                          [곱슬이콩나물 1박스]
                        3500.0                              [일미 콩자반]
                        3550.0                             [일미 양념깻잎]
                        13450.0                             [양념소불고기]
                        14580.0                            [토속대란 1판]
2021-09-11 3       6    400.0                            [롯데 레쓰비마일드]
                        7640.0                               [황태채 대]
           4       6    500.0                                  [흙당근]
                        2980.0                             [영양쏙쏙김밥햄]
           5       6    990.0                          [풀무원  소가찌개두부]
                        4520.0                         [국내산앞다리살/찌개용]
           6       6    750.0                             [조지아 카페라떼]
                        990.0                           [해태 골든흑당밀크티]
           7       6    620.0                           [재사용봉투(20L)]
                        1100.0                                 [삼다수]
                        1280.0                                [처음처럼]
                        1650.0                            [카스캔355ml]
                        1750.0                             [해태 킨사이다]
                        2500.0                                [쌀소성주]
           8       6    15000.0                      [*송산포도 3kg/1박스]
2021-09-12 3       6    990.0                        [남양 프렌치카페 마키야또]
                        11910.0                          [양념돈고추장주물럭]
           4       6    17000.0                               [프라이드]
           5       6    29800.0                           [마늘 50입이내]
           6       6    850.0                            [롯데 짱셔요후르츠]
                        1380.0                       [삼양 까르보나라불닭볶음컵]
                        1480.0                        [농심 신라면볶음면큰사발]
           7       6    700.0                             [*비름나물 1단]
                        1980.0                        [*어플행사 양상추/벌크]
           8       6    700.0                             [*비름나물 1단]
                        1980.0                        [*어플행사 양상추/벌크]
2021-09-13 3       6    1990.0                           [서울 스타벅스라떼]
           4       6    2250.0                                [박카스F]
           5       6    950.0                               [CJ 맛소금]
                        9500.0                            [(현미)찰고추장]
2021-09-14 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    1980.0                           [오뚜기 옛날육개장]
           5       6    990.0                     [CJ노릇하게잘구워지는부침두부 ]
                        1980.0                              [*대파 1단]
           6       6    980.0                      [롯데 칸타타 콜드브루흑당라떼]
                        2280.0                          [곱슬이콩나물 1박스]
                        7400.0                            [단지 반달단무지]
                        8900.0                           [깐메추리알 1kg]
                        11810.0                          [양념돈고추장주물럭]
                        36000.0                                [유니랩]
           7       6    1250.0                            [오뚜기 양조식초]
                        8900.0                         [풀무원 자연란 유정란]
           8       6    2500.0                            [*가지 5입/봉]
                        3680.0                        [오뚜기 진라면컵 매운맛]
                        4500.0                             [둥근호박 1개]
                        5100.0                           [농심 안성탕면 컵]
                        6300.0                        [오뚜기 참깨라면 미니컵]
2021-09-15 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    9460.0                           [대패삼겹살(수입)]
           5       6    1000.0                         [롯데 레쓰비그란데라떼]
           6       6    990.0                            [오뚜기 옛날육개장]
                        1250.0                              [햇반작은공기]
2021-09-16 3       6    400.0                            [롯데 레쓰비마일드]
                        1500.0                     [*무우 1개(봉)(투명비닐)]
                        3850.0                            [백설/진한참기름]
           4       6    2250.0                                [박카스F]
           5       6    7290.0                             [토속대란 1판]
2021-09-17 3       6    2850.0                            [광동 비타500]
           4       6    1000.0                              [순두부 1봉]
                        2980.0                             [*백오이 3개]
                        3960.0                           [대림 신선한콩두부]
                        5940.0                          [*깻잎(4묶음)/봉]
           5       6    1780.0                           [서울 스페셜마일드]
           6       6    1980.0                             [남양 이오기획]
           7       6    400.0                            [롯데 레쓰비마일드]
           8       6    1350.0                              [참이슬후레쉬]
                        2500.0                            [해맑음 종합젤리]
                        2780.0                            [좋은세상 통산자]
                        2980.0                               [오양 맛살]
                        4900.0                           [국순당 예담차례주]
                        5000.0                           [좋은세상 왕손약과]
                        7600.0                               [황태포 왕]
                        14580.0                            [토속대란 1판]
           9       6    990.0          [CJ 삼호부산어묵바른사각, 청정원 숨쉬는전통콩나물]
                        3960.0                          [*깻잎(4묶음)/봉]
                        4590.0                                [표고버섯]
2021-09-18 3       6    16000.0                            [원더독스스페셜]
           4       6    400.0                            [롯데 레쓰비마일드]
           5       6    1500.0                            [운수대통대나무술]
                        3950.0                         [풀무원 찬마루깻잎무쌈]
           6       6    2850.0                            [광동 비타500]
           7       6    1980.0                          [청정원 소갈비양념장]
                        5980.0                              [백설맛술생강]
           8       6    1550.0                         [CJ행복한콩/반모두부]
                        1880.0                         [행복한콩/아삭통통숙주]
                        3020.0                                 [토란대]
                        3980.0                                [영양부추]
                        5340.0                                  [연근]
                        19080.0                             [국내산돈목살]
2021-09-19 3       6    990.0                          [남양 또떠불 눈꽃쵸코]
                        1380.0                       [삼양 까르보나라불닭볶음컵]
           5       6    3300.0                            [서울 목장의우유]
                        19110.0                             [양념소불고기]
           6       6    990.0                          [풀무원  소가찌개두부]
           7       6    8100.0                              [참이슬클래식]
                        35000.0             [*타임*문장대포도(등급:상)3kg/1박스]
           8       6    31200.0                           [화미 이온고백당]
2021-09-20 3       6    2650.0                               [칠성사이다]
                        2700.0                            [롯데 제로사이다]
                        2980.0                              [*대파 1단]
           4       6    980.0                            [동부묵  400g]
                        1500.0                    [알배기/쌈배추, 알배기/쌈배추]
                        1960.0                             [알배기/쌈배추]
                        1980.0                   [CJ 튀김가루, 오뚜기 튀김가루]
                        2980.0                             [*단호박 1개]
                        3980.0                          [청정원 요리올리고당]
                        4850.0                         [오뚜기 옛날참기름 캔]
                        6980.0                             [토속대란 1판]
           5       6    2000.0                                 [흙당근]
                        2500.0                         [풀무원 씻어나온콩나물]
                        2940.0                         [롯데 칸타타 더치블랙]
                        5410.0                         [CJ태양초골드고추장 ]
           6       6    1980.0                            [*청양고추(소)]
2021-09-22 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    1960.0                           [서울 요구르트제로]
2021-09-23 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    990.0                           [풀무원 소가부침두부]
                        2200.0                             [국순당 우국생]
           5       6    1980.0                         [롯데 꼬깔콘 매콤달콤]
           6       6    15800.0                          [*양파 15kg/]
2021-09-24 3       6    2850.0                            [광동 비타500]
                        4000.0                                  [참외]
           4       6    400.0                            [롯데 레쓰비마일드]
                        2500.0                              [*대파 1단]
           5       6    25000.0            [(옹골찬,김천,무을)샤인머스켓2kg/1박스]
2021-09-25 3       6    400.0                          [롯데 레쓰비 모카라떼]
           4       6    550.0                           [롯데 레쓰비 마일드]
           5       6    950.0                            [몽글몽글봉지순두부]
                        1500.0                               [공주알밤술]
           6       6    400.0                               [맛있는연두부]
                        1400.0                          [**인큐애호박 1개]
                        1480.0                           [*느타리버섯 2팩]
                        1580.0                          [심층수손두부/550]
                        1710.0                                  [감자]
                        2250.0                        [삼립 56시간저온숙성숙]
           7       6    3000.0                   [행복한콩/2가지로만 국산콩찌개용]
                        5900.0                           [장가가는마된장찌개]
           8       6    620.0                           [재사용봉투(20L)]
                        2000.0                          [*깻잎(4묶음)/봉]
                        2100.0                          [**인큐애호박 1개]
                        2500.0                [백오이, *바나나/1봉(송이)(행사)]
                        3960.0                            [*가지 5입/봉]
                        6180.0                          [좋은세상 조미오징어]
                        9800.0                        [*적상추 2kg/1박스]
                        10140.0                             [오징어 덕용]
           9       6    3700.0                          [동원 고등어 원터치]
2021-09-26 3       6    2500.0    [삼립 아침미소토스트앤샌드위치, *바나나/1봉(송이)(행사)]
                        3980.0                          [CJ해찬들 초고추장]
                        5300.0                               [칠성사이다]
           4       6    1980.0                            [*가지 5입/봉]
           6       6    1500.0                            [*파프리카/1개]
                        2500.0                        [CJ 행복한콩 큰두부 ]
                        3680.0                         [빙그레 굿모닝우유기획]
           7       6    3380.0                          [일미 비타에이단무지]
                        3500.0                           [목우촌 불에김밥햄]
2021-09-27 3       6    2850.0                            [광동 비타500]
                        7100.0                              [듀라셀알카D]
           4       6    2000.0                             [바나나, 쪽파]
                        2480.0                        [남양 프로바이오틱 사과]
                        2500.0                            [*가지 5입/봉]
                        3750.0                                [쌀소성주]
2021-09-28 3       6    2280.0                          [곱슬이콩나물 1박스]
                        23940.0                            [토속대란 1판]
           5       6    550.0                           [롯데 레쓰비 마일드]
                        600.0                             [모나리자 여행용]
           6       6    1280.0                     [*무우 1개(봉)(투명비닐)]
                        1600.0                         [풀무원 씻어나온콩나물]
                        1800.0                              [*대파 1단]
                        2780.0                         [롯데 트레비 라임기획]
                        2980.0                              [*양파(소)]
           7       6    3200.0                            [빙그레 요구르트]
           8       6    400.0                            [롯데 레쓰비마일드]
           9       6    1000.0                          [후레시아물티슈 캡형]
                        2380.0                            [해표 중력밀가루]
                        4980.0                          [오뚜기 옛날국수중면]
                        6800.0                          [CJ 햇반기획 6입]
2021-09-29 3       6    400.0                            [롯데 레쓰비마일드]
                        1500.0                                 [양배추]
                        2080.0                    [CJ 부침가루, CJ 튀김가루]
                        3980.0                        [*망고수박 1통(행사)]
           4       6    550.0                           [롯데 레쓰비 마일드]
                        1000.0                           [*쥬키니호박 1개]
2021-09-30 3       6    400.0                            [롯데 레쓰비마일드]
                        2500.0                         [풀무원 씻어나온콩나물]
           4       6    1980.0                        [단호박(미니), 홍고추]
                        3380.0                        [소와나무 고칼슘우유기획]
           5       6    1500.0                   [행복한콩/2가지로만 국산콩찌개용]
2021-10-01 3       6    40.0                                  [배달봉투]
                        400.0                            [롯데 레쓰비마일드]
                        2980.0                              [*양파(소)]
                        3580.0                           [농심 신라면 멀티]
                        3960.0                        [칠갑 우리쌀국수 멸치맛]
                        14880.0                        [참이슬후레쉬640ml]
                        39500.0                                [고덕쌀]
           5       6    3980.0                           [서울 스타벅스라떼]
2021-10-02 3       6    400.0                            [롯데 레쓰비마일드]
                        2000.0                            [*아보카도/1개]
2021-10-03 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    2700.0                               [서울 우유]
                        5000.0                              [*단감/5개]
2021-10-04 3       6    2250.0                                [박카스F]
2021-10-05 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    2900.0                               [서울 우유]
2021-10-06 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    1580.0                            [국산콩나물(봉)]
2021-10-07 3       6    400.0                            [롯데 레쓰비마일드]
                        2580.0                          [오뚜기 짜장면 멀티]
                        3280.0                        [피죤 핑크로즈기획 용기]
2021-10-08 3       6    400.0                            [롯데 레쓰비마일드]
                        2980.0                       [CJ 삼호요리어묵국탕종합]
2021-10-09 3       6    400.0                            [롯데 레쓰비마일드]
           4       6    1850.0                          [동원 고등어 원터치]
                        1860.0                               [우도땅콩술]
           5       6    620.0                           [재사용봉투(20L)]
                        2100.0                         [LG 퐁퐁 베이킹소다]
                        2460.0                        [CJ 햇반컵반 미역국밥]

In [25]:
amartsumgr1.query('hour == 7')

                                                                          GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 3       7    990.0                                        [동원 골든스위트콘]
                        2150.0                                         [청정원 맛소금]
                        216000.0                                     [구호물품 포장박스]
                        360000.0  [오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 종가집 볶음김치캔, 종가집 김치캔]
                        450000.0                                 [오뚜기 진라면 순한 멀티]
...                                                                          ...
2022-09-01 15      7    3500.0                               [쑥갓, *호박고구마 1봉(비닐)]
                        3950.0                                       [*쪽파(소) 1단]
                        6500.0                                         [토속대란 1판]
                        8900.0                                       [*알타리무 1박스]
                        10420.0                                       [돌파래자반[대]]

[16577 rows x 1 columns]

In [26]:
amartsumgr1.query('hour == 10')

                                                    GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 1       10   1000.0                  [*청양고추(소)]
                        1280.0                    [*대파 1단]
                        2500.0     [*꽈리고추 (500g), *백오이 3개]
                        2850.0                 [CJ 안심김밥맛살]
                        2980.0                    [*양파(소)]
...                                                    ...
2022-09-01 139     10   5300.0                    [썬 부탄가스]
           140     10   3980.0    [오리온 팝크랜베리, 오그래놀라팝현미아몬드]
                        4980.0                  [맛간장조림볶음용]
           141     10   5500.0                  [*쪽파(대)1단]
           142     10   750.0                 [재사용봉투(20L)]

[253713 rows x 1 columns]

In [27]:
amartsumgr1.query('hour == 14')

                                                       GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 12      14   980.0                     [*느타리버섯 2팩]
                        3960.0                      [*양배추 1통]
                        5960.0                 [가지 5개(벌크)/행사]
                        7000.0                   [해표 올리브유김자반]
                        11800.0          [칠곡자두(왕)5kg/1박스(행사)]
...                                                       ...
2022-09-01 295     14   1760.0                          [흙당근]
                        1980.0    [크라운 마이쮸딸기 번들, 크라운 마이쮸사과번들]
                        2530.0                           [감자]
                        2950.0                    [*양파(중) 1망]
                        9800.0                      [*홍고추 1봉]

[399897 rows x 1 columns]

In [28]:
amartsumgr1.query('hour == 17')

                                                 GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-01 20      17   2500.0               [*청양고추 1k]
                        15800.0             [*양파 15kg/]
                        19600.0            [농심 사리면 BOX]
                        24000.0              [*대파(10단)]
           38      17   620.0              [재사용봉투(20L)]
...                                                 ...
2022-09-01 471     17   3500.0               [롯데 칠성사이다]
                        3900.0             [오뚜기 육개장컵기획]
                        3980.0    [CJ 햇자른당면, LG 자연퐁 솔잎]
                        4980.0             [크라운 국희 2번들]
                        10800.0     [퍼실파워젤일반, 코디)뉴테코3겹]

[503123 rows x 1 columns]

-----------------------------------

In [31]:
amartsumgr1monday = amartsumgr1.query('SAL_DT.dt.dayofweek == 0') # 월요일 데이터만
amartsumgr1monday

                                                       GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-06 1       11   1350.0    [서울 비요뜨 초코팝, 서울 비요뜨 초코크리스피]
                        2500.0                      [백설 갈색설탕]
                        2980.0                       [*양파(소)]
                        3980.0                     [송학 감자수제비]
                        4380.0                   [오뚜기 진짬뽕 멀티]
...                                                       ...
2022-08-29 658     21   1000.0                       [서주 빵뚜르]
                        1200.0                        [바밤바샌드]
           659     21   1250.0                [*수입산)브로컬리 1송이]
                        3950.0                      [*청상추 1봉]
           660     21   10850.0                    [농심 우와한콩칩]

[618767 rows x 1 columns]

In [35]:
amartsumgr1monday.query('hour == 6').head(30) # 월요일 데이터 중 6시만

                                               GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-06 3       6    1200.0      [롯데 칸타타 아이스아메리카노]
                        1400.0            [푸드마크 암반얼음]
                        4980.0          [*양배추(4*5)1망]
           4       6    4980.0                 [명품사과]
           5       6    2960.0      [*무우 1개(봉)(투명비닐)]
2021-09-13 3       6    1990.0            [서울 스타벅스라떼]
           4       6    2250.0                 [박카스F]
           5       6    950.0                [CJ 맛소금]
                        9500.0             [(현미)찰고추장]
2021-09-20 3       6    2650.0                [칠성사이다]
                        2700.0             [롯데 제로사이다]
                        2980.0               [*대파 1단]
           4       6    980.0             [동부묵  400g]
                        1500.0     [알배기/쌈배추, 알배기/쌈배추]
                        1960.0              [알배기/쌈배추]
                        1980.0    [CJ 튀김가루, 오뚜기 튀김가루]
                        2980.0              [*단호박 1개]
                        3980.0           [청정원 요리올리고당]
                        4850.0          [오뚜기 옛날참기름 캔]
                        6980.0              [토속대란 1판]
           5       6    2000.0                  [흙당근]
                        2500.0          [풀무원 씻어나온콩나물]
                        2940.0          [롯데 칸타타 더치블랙]
                        5410.0          [CJ태양초골드고추장 ]
           6       6    1980.0             [*청양고추(소)]
2021-09-27 3       6    2850.0             [광동 비타500]
                        7100.0               [듀라셀알카D]
           4       6    2000.0              [바나나, 쪽파]
                        2480.0         [남양 프로바이오틱 사과]
                        2500.0             [*가지 5입/봉]

In [34]:
amartsumgr1monday['GDS_NM'].value_counts() # 월요일 기준 제일 많이 팔린 것

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[재사용봉투(20L)]                     17904
[배달봉투]                            6990
[*대파 1단]                          6195
[*백오이 1개]                         4656
[흙당근]                             4593
                                 ...
[애경 순샘 레몬 파우치, 필라이트]                 1
[삼양라면 멀티, 청정원 두번달여더진한 진간장 ]          1
[CJ더건강한직화구이햄, 해표 고소한참기름]             1
[조미어채, 좋은세상 통산자]                     1
[깐메추리알/행사, *왕스치딸기/1kg/박스(행사)]        1
Name: GDS_NM, Length: 42174, dtype: int64

In [36]:
amartsumgr1Tue = amartsumgr1.query('SAL_DT.dt.dayofweek == 1') # 화요일 데이터만
amartsumgr1Tue

                                                     GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-07 1       10   1980.0            [*대파 1단, 롯데 초코파이]
                        3980.0    [남양 맛있는우유GT기획, *양파(중) 1망]
                        5900.0                  [오뚜기 옛날다시마]
                        12400.0                      [돈삼겹살]
                        13500.0              [풀무원 항생제통통신선란]
...                                                     ...
2022-08-30 582     21   3500.0                        [바나나]
                        5200.0                 [빙그레 바나나맛우유]
                        7980.0                    [풀무원 목초란]
           583     21   3980.0               [소와나무 고칼슘우유기획]
           584     21   1950.0                   [*고구마순 1단]

[565333 rows x 1 columns]

In [37]:
amartsumgr1Tue['GDS_NM'].value_counts() # 화요일 기준 제일 많이 팔린 것

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[재사용봉투(20L)]                                                            16687
[*대파 1단]                                                                 6709
[배달봉투]                                                                   6458
[서울 우유]                                                                  4121
[흙당근]                                                                    4063
                                                                        ...
[*단호박 1개, *백오이 3개, *조림감자 1봉/비닐(행사), *수입산)브로컬리 2송이구입시(행사)]                   1
[오리온 치킨팝, 파채]                                                               1
[심층수두부(대), 농심 새우깡 블랙]                                                       1
[해태 누가바, 롯데 와일드바디, 롯데 돼지바, 롯데 옥동자, 롯데 보석바, 서주 메론바, 서주 아이스주, 롯데 스크류바]        1
[오뚜기 진라면 순한 용기, 오뚜기 튀김우동컵, 오뚜기 스낵면컵, 오리온 다이제초코미니]                           1
Name: GDS_NM, Length: 39356, dtype: int64

In [45]:
amartsumgr1Tue.query('TRAN_NO == 1').head(30)

                                                                             GDS_NM
SAL_DT     TRAN_NO hour SALE_AMT
2021-09-07 1       10   1980.0                                    [*대파 1단, 롯데 초코파이]
                        3980.0                            [남양 맛있는우유GT기획, *양파(중) 1망]
                        5900.0                                          [오뚜기 옛날다시마]
                        12400.0                                              [돈삼겹살]
                        13500.0                                      [풀무원 항생제통통신선란]
2021-09-14 1       11   700.0                                     [*무우 1개(봉)(투명비닐)]
                        980.0                                             [오양 파티맛살]
                        990.0                                       [남양 프렌치카페 카푸치노]
                        1900.0                                             [CJ 맛소금]
                        1980.0    [*새송이버섯 1봉, *깻잎(4묶음)/봉, 쏘피 천연코튼라이너 일반라벤더, CJ 부...
                        2100.0                                     [농심 신라면두부김치블랙사발]
                        2280.0                                          [오뚜기 소갈비양념]
                        2480.0                             [남양 프로바이오틱 사과, 백설소불고기양념]
                        2500.0                                       [CJ 행복한콩 큰두부 ]
                        2550.0                                     [LG 토디앙네이처그린 캡형]
                        3000.0                                        [서울 아침에오렌지쥬스]
                        3500.0                                          [*쪽파(소) 1단]
                        3980.0                                          [*양파(중) 1망]
                        4180.0                                        [홈스타 욕실용 세정제]
                        4350.0                                          [오뚜기 요리매실청]
                        4500.0                                      [*깐마늘350g이내/국산]
                        4980.0                              [동원 자연산골뱅이, 오뚜기 옛날자른당면]
                        7500.0                                           [목우촌 살코기햄]
                        7960.0                                          [쌈배추(벌크)1통]
                        8900.0                                       [다우니 블루 튤립라일락]
                        9800.0                                        [*스치)느타리 1박스]
                        19800.0                                           [w화이트슈퍼롱]
2021-09-28 1       10   1700.0                                           [농심 김치사발면]
                        1980.0                                           [오리온 땅콩강정]
                        2580.0                                           [크라운 버터와플]

## 월별 요일별 시간별 어떤 상품이 가장 많이 팔렸는데 알고싶은데 방법 찾는중

## 회원번호로 매칭을 해볼까 했는데 a 마트만 회원번호가 있고 bcd 는 의미가없음 아예 없는 매장도 있고 의미있는 추출이 불가능 이라는 결론